#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Create lang_sources/*.json with 292 keys per language."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "lang_sources"
OUT.mkdir(exist_ok=True)

FORMAT = {
    "%@ – %@": "%1$@ – %2$@",
    "%@ · %@": "%1$@ · %2$@",
    "%@ (%@)": "%1$@ (%2$@)",
    "%@ %@": "%1$@ %2$@",
    "%@: %@": "%1$@: %2$@",
}

def lang_names(prefix):
    return {f"language.{k}": v for k, v in prefix.items()}

def base(t):
    d = dict(FORMAT)
    d.update({
        "Enter a weight between %@ and %@.": t["Enter a weight between %@ and %@."],
        "Step %lld of %lld": t["Step %lld of %lld"],
        "app.name": "Bloomly",
        "babySize.sharePartner": t["Share with Partner"],
        "bumpJournal.camera": t["Camera"],
        "bumpJournal.empty.subtitle": t["Add your first photo to start your visual journal."],
        "bumpJournal.empty.title": t["No bump photos yet"],
        "bumpJournal.optionalNote": t["Optional note"],
        "bumpJournal.photoLibrary": t["Photo Library"],
        "bumpJournal.savePhoto": t["Save Photo"],
        "bumpJournal.subtitle": t["Capture your growing bump each week and watch your journey unfold."],
        "bumpJournal.weekBump %lld": t["Week %lld Bump"],
        "common.back": t["Back"],
        "common.cancel": t["Cancel"],
        "common.continue": t["Continue"],
        "common.date": t["Date"],
        "common.done": t["Done!"],
        "common.gender": t["Gender"],
        "common.history": t["History"],
        "common.letter": t["Letter"],
        "common.log": t["Log"],
        "common.logged": t["Logged"],
        "common.ok": "OK",
        "common.ongoing": t["ongoing"],
        "common.optional": t["(optional)"],
        "common.pause": t["Pause"],
        "common.premiumFeature %@": t["%@ is part of Bloomly Plus"],
        "common.reset": t["Reset"],
        "common.save": t["Save"],
        "common.severity": t["Severity"],
        "common.start": t["Start"],
        "common.style": t["Style"],
        "common.upgrade": t["Upgrade"],
        "common.weekNumber %lld": t["Week %lld"],
        "cycle.periodEnded": t["Period ended"],
        "dailyLog.daySummary": t["Day Summary"],
        "dailyLog.notes": t["Notes"],
        "dailyLog.title": t["Daily Log"],
        "home.dailyGoalWater": t["Daily goal: 8 glasses"],
        "home.dailyTip": t["Daily Tip"],
        "home.daysUntilDue %lld": t["%lld days until due date"],
        "home.dueDatePassed": t["Your due date has passed"],
        "home.glassesOfWater": t["glasses of water"],
        "home.howFeeling": t["How are you feeling?"],
        "home.mood": t["Mood"],
        "home.planningMode": t["Planning Mode"],
        "home.planningSubtitle": t["Track your cycle and prepare for your journey."],
        "home.pregnancyProgress": t["Pregnancy Progress"],
        "home.quickLog": t["Quick Log"],
        "home.symptoms": t["Symptoms"],
        "home.title": t["Home"],
        "home.water": t["Water"],
        "home.waterIntake": t["Water Intake"],
        "home.weekOfTotal %lld": t["Week %lld of 40"],
        "home.weight": t["Weight"],
        "onboarding.dates.dueDate": t["Due date"],
        "onboarding.dates.lastPeriod": t["Last period"],
        "onboarding.dates.lastPeriodStart": t["Last period start"],
        "onboarding.dates.lmpLabel": t["Last menstrual period"],
        "onboarding.dates.planning.subtitle": t["When did your last period start? You can log more dates anytime."],
        "onboarding.dates.planning.tip": t["Cycle insights appear on your Home tab"],
        "onboarding.dates.planning.title": t["Track your cycle"],
        "onboarding.dates.pregnant.subtitle": t["We'll calculate your week and due date."],
        "onboarding.dates.pregnant.title": t["When did your journey begin?"],
        "onboarding.feature.guides.subtitle": t["Baby size, tips & milestones"],
        "onboarding.feature.guides.title": t["Week-by-week guides"],
        "onboarding.feature.logging.subtitle": t["Symptoms, mood, water & more"],
        "onboarding.feature.logging.title": t["Daily wellness logging"],
        "onboarding.feature.privacy.subtitle": t["Your data never leaves your phone"],
        "onboarding.feature.privacy.title": t["100% on your device"],
        "onboarding.getStarted": t["Get Started"],
        "onboarding.mode.planning.subtitle": t["Cycle tracking, fertile windows & prep"],
        "onboarding.mode.planning.title": t["I'm planning"],
        "onboarding.mode.pregnant.subtitle": t["Track weeks, baby size, kicks & milestones"],
        "onboarding.mode.pregnant.title": t["I'm pregnant"],
        "onboarding.mode.subtitle": t["We'll tailor Bloomly to your stage."],
        "onboarding.mode.title": t["What brings you here?"],
        "onboarding.prefs.dailyReminders": t["Daily reminders"],
        "onboarding.prefs.firstPregnancy": t["First pregnancy?"],
        "onboarding.prefs.firstPregnancyToggle": t["This is my first pregnancy"],
        "onboarding.prefs.notificationHint": t["We'll ask for notification permission when you finish setup."],
        "onboarding.prefs.startingWeight": t["Starting weight"],
        "onboarding.prefs.startingWeightHint": t["Pre-pregnancy weight helps track healthy gain over time."],
        "onboarding.prefs.subtitle": t["A few quick preferences to personalize Bloomly."],
        "onboarding.prefs.title": t["Almost there!"],
        "onboarding.prefs.weightUnit": t["Weight unit"],
        "onboarding.step.dates": t["Key dates"],
        "onboarding.step.journey": t["Your journey"],
        "onboarding.step.preferences": t["Preferences"],
        "onboarding.step.welcome": t["Welcome"],
        "onboarding.stepOf %lld %lld": t["Step %lld of %lld"],
        "onboarding.welcome.subtitle": t["A calm, private space to track every moment — from first flutter to final countdown."],
        "onboarding.welcome.title": t["Your journey starts here"],
        "partner.dueDatePassed": t["Due date has passed — any day now!"],
        "partner.forName %@": t["— For %@"],
        "partner.messagePlaceholder": t["Can't wait to meet our little one!"],
        "partner.personalMessage": t["Personal message"],
        "partner.shareImage": t["Share Image"],
        "partner.shareLine %lld": t["🌸 Bloomly — Week %lld"],
        "partner.sharePreview %lld": t["Bloomly Week %lld"],
        "partner.shareText": t["Share Text Update"],
        "partner.shareTitle": t["Share Update"],
        "paywall.feature.appointments": t["Appointments with reminders"],
        "paywall.feature.nutrition": t["Trimester-aware nutrition guide"],
        "paywall.feature.statistics": t["Statistics & history charts"],
        "paywall.feature.symptoms": t["Full symptom & weight logging"],
        "paywall.feature.tools": t["Wellness tools: Kegel, kick & contraction timers"],
        "paywall.purchaseError": t["Purchase could not be completed."],
        "paywall.restore": t["Restore Purchases"],
        "paywall.startFree": t["Start Free"],
        "paywall.subscriptionsPlaceholder": t["Subscriptions will appear when configured in App Store Connect."],
        "paywall.subtitle": t["Unlock the full wellness experience"],
        "paywall.title": "Bloomly Plus",
        "profile.account": t["Account"],
        "profile.appointments": t["Appointments"],
        "profile.babyNames": t["Baby Names"],
        "profile.bloomlyPlus": "Bloomly Plus",
        "profile.bumpJournal": t["Bump Journal"],
        "profile.cycleTracker": t["Cycle Tracker"],
        "profile.dailyReminders": t["Daily Reminders"],
        "profile.dueDate": t["Due Date"],
        "profile.favorites": t["Favorites"],
        "profile.features": t["Features"],
        "profile.free": t["Free"],
        "profile.logPeriod": t["Log Period"],
        "profile.mode": t["Mode"],
        "profile.newAppointment": t["New Appointment"],
        "profile.noAppointments": t["No upcoming appointments"],
        "profile.nutrition": t["Nutrition Guide"],
        "profile.partnerHint": t["Used when sharing weekly baby-size updates."],
        "profile.partnerName": t["Partner's name (optional)"],
        "profile.partnerSharing": t["Partner Sharing"],
        "profile.past": t["Past"],
        "profile.planning": t["Planning"],
        "profile.pregnant": t["Pregnant"],
        "profile.premium": t["Premium"],
        "profile.privacy": t["Privacy"],
        "profile.privacyBody": t["Bloomly stores all your data exclusively on your device."],
        "profile.privacyBullet1": t["Collect any personal data"],
        "profile.privacyBullet2": t["Send data to servers or the cloud"],
        "profile.privacyBullet3": t["Use analytics or tracking SDKs"],
        "profile.privacyBullet4": t["Show advertisements"],
        "profile.privacyBullet5": t["Require an account or login"],
        "profile.privacyFooter": t["Your data never leaves your iPhone unless you back up via iCloud or iTunes."],
        "profile.privacyTitle": t["Your Privacy Matters"],
        "profile.privacyWeDoNot": t["We do not:"],
        "profile.settings": t["Settings"],
        "profile.sharePartner": t["Share with Partner"],
        "profile.statistics": t["Statistics"],
        "profile.title": t["Profile"],
        "profile.upcoming": t["Upcoming"],
        "profile.upgrade": t["Upgrade to Bloomly Plus"],
        "profile.week": t["Week"],
        "profile.weightTracker": t["Weight Tracker"],
        "profile.yourName": t["Your name (optional)"],
        "reminders.breakfast": t["Breakfast"],
        "reminders.dinner": t["Dinner"],
        "reminders.footer": t["Daily local reminders to help you stay hydrated and eat on schedule."],
        "reminders.lunch": t["Lunch"],
        "reminders.mealReminders": t["Meal Reminders"],
        "reminders.mealSchedule": t["Meal Schedule"],
        "reminders.notificationsDisabled": t["Notifications are disabled. Tap here to open Settings and enable them for Bloomly."],
        "reminders.snack": t["Snack"],
        "reminders.waterReminders": t["Water Reminders"],
        "reminders.waterSchedule": t["Water Schedule"],
        "settings.appearance": t["Appearance"],
        "settings.appearance.subtitle": t["Choose a color theme for your app"],
        "settings.language": t["Language"],
        "settings.language.footer": t["Content like week guides will stay in English until translated."],
        "splash.tagline": t["Your pregnancy companion"],
        "stats.best": t["Best"],
        "stats.current": t["Current"],
        "stats.details": t["Details"],
        "stats.fertileWindow": t["Fertile Window"],
        "stats.gain": t["Gain"],
        "stats.moodHistory": t["Mood History"],
        "stats.nextPeriod": t["Next Period"],
        "stats.noSymptomData": t["No symptom data yet"],
        "stats.noWeightData": t["No weight data yet. Log from Home or Weight Tracker."],
        "stats.ovulationEstimate": t["Ovulation Estimate"],
        "stats.prediction": t["Prediction"],
        "stats.symptomFrequency": t["Symptom Frequency"],
        "stats.waterStreak": t["Water Streak"],
        "stats.weightOverTime": t["Weight Over Time"],
        "tab.dailyLog": t["Daily Log"],
        "tab.home": t["Home"],
        "tab.profile": t["Profile"],
        "tab.tools": t["Tools"],
        "tab.weekGuide": t["Week Guide"],
        "theme.blush": t["Blush"],
        "theme.coral": t["Coral"],
        "theme.dark": t["Dark"],
        "theme.forest": t["Forest"],
        "theme.lavender": t["Lavender"],
        "theme.midnight": t["Midnight"],
        "theme.mint": t["Mint"],
        "theme.peach": t["Peach"],
        "theme.rain": t["Rain"],
        "theme.roseGold": t["Rose Gold"],
        "theme.sunset": t["Sunset"],
        "theme.white": t["White"],
        "tools.contraction.duration %@": t["Duration: %@"],
        "tools.contraction.interval %@": t["Interval: %@"],
        "tools.contraction.start": t["Start Contraction"],
        "tools.contraction.stop": t["Stop Contraction"],
        "tools.contractionSubtitle": t["Time contractions"],
        "tools.contractionTimer": t["Contraction Timer"],
        "tools.hydration": t["Hydration"],
        "tools.hydration.logFromHome": t["Log water from the Home tab quick actions"],
        "tools.hydrationSubtitle": t["Visual water counter"],
        "tools.kegel.complete": t["Complete!"],
        "tools.kegel.hold": t["Hold"],
        "tools.kegel.instructions": t["Hold for 5 seconds, release for 5 seconds"],
        "tools.kegel.ready": t["Ready"],
        "tools.kegel.release": t["Release"],
        "tools.kegel.repOf %lld": t["Rep %lld of 10"],
        "tools.kegel.rest": t["Rest"],
        "tools.kegel.setOf %lld": t["Set %lld of 3"],
        "tools.kegelSubtitle": t["3 sets × 10 reps"],
        "tools.kegelTimer": t["Kegel Timer"],
        "tools.kick.kicks": t["kicks"],
        "tools.kick.saveSession": t["Save Session"],
        "tools.kick.tapForKick": t["Tap for Kick"],
        "tools.kickCounter": t["Kick Counter"],
        "tools.kickSubtitle": t["Track baby movements"],
        "tools.title": t["Tools"],
        "tools.weightSubtitle": t["Log weight & view trends"],
        "tools.weightTracker": t["Weight Tracker"],
        "tools.wellnessGate": t["Wellness tools"],
        "weekGuide.appointment": t["Appointment"],
        "weekGuide.development": t["Development"],
        "weekGuide.length": t["Length"],
        "weekGuide.momFeeling": t["How You May Feel"],
        "weekGuide.tip": t["Tip"],
        "weekGuide.title": t["Week Guide"],
        "weekGuide.weight": t["Weight"],
        "weight.fieldPlaceholder": t["Weight"],
        "weight.guidance %lld": t["Week %lld Guidance"],
        "weight.historyEmpty": t["Your weight entries will appear here."],
        "weight.invalidTitle": t["Invalid Weight"],
        "weight.invalidUnit %@": t["Please enter a valid weight in %@."],
        "weight.latest": t["Latest"],
        "weight.logTitle": t["Log Weight"],
        "weight.logWeight": t["Log Weight"],
        "weight.notLoggedYet": t["Not logged yet"],
        "weight.noWeightYet": t["No weight logged yet"],
        "weight.orEnterManually": t["Or enter manually"],
        "weight.prePregnancy": t["Pre-pregnancy"],
        "weight.previousEntry": t["Previous entry"],
        "weight.range %@ %@": t["Enter a weight between %@ and %@."],
        "weight.set": t["Set"],
        "weight.sinceLast": t["Since Last"],
        "weight.sinceLastEntry %@": t["%@ since last entry"],
        "weight.sinceStarting": t["Since starting weight"],
        "weight.sinceStartingWeight %@": t["%@ since starting weight"],
        "weight.starting": t["Starting"],
        "weight.startingSubtitle": t["Your pre-pregnancy weight helps track healthy gain over time."],
        "weight.startingTitle": t["Starting Weight"],
        "weight.startingWeightTip": t["Tip: set your starting weight in the Weight Tracker for gain tracking."],
        "weight.tapToAdd": t["Tap to add"],
        "weight.totalChange": t["Total Change"],
        "weight.trend": t["Weight Trend"],
    })
    return d

from _lang_tables import TABLES  # noqa: E402

for code, (names, table) in TABLES.items():
    data = base(table)
    data.update(lang_names(names))
    path = OUT / f"{code}.json"
    path.write_text(json.dumps(dict(sorted(data.items())), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {code}: {len(data)} keys")
