#!/usr/bin/env python3
"""Generate lang_data/week_guide/*.json translation files."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "lang_data" / "week_guide"

T: dict[str, dict[str, str]] = {
    "es": {
        "weekGuide.development %lld": "La semana %lld trae nuevos hitos de crecimiento. Los órganos y sistemas de tu bebé siguen desarrollándose rápidamente durante esta etapa del embarazo.",
        "weekGuide.momFeeling %lld": "Puedes notar cambios en tu energía y sensaciones corporales típicas de la semana %lld. Escucha a tu cuerpo y descansa cuando lo necesites.",
        "weekGuide.tip": "Mantente hidratada y come comidas equilibradas esta semana. Los bocadillos pequeños y frecuentes pueden ayudar a tu bienestar.",
        "weekGuide.appointment.firstPrenatal": "La primera visita prenatal suele programarse entre las semanas 8 y 10",
        "weekGuide.appointment.nuchal": "La prueba de translucencia nucal puede ofrecerse alrededor de la semana 12",
        "weekGuide.appointment.anatomy": "La ecografía anatómica suele realizarse alrededor de la semana 20",
        "weekGuide.appointment.glucose": "La prueba de glucosa suele recomendarse entre las semanas 24 y 28",
        "weekGuide.appointment.thirdTrimester": "Las revisiones del tercer trimestre pueden aumentar en frecuencia",
        "weekGuide.appointment.weeklyVisits": "Las visitas semanales suelen comenzar alrededor de la semana 36",
        "dailyTip.fallback": "Descansa cuando lo necesites: tu cuerpo está haciendo un trabajo increíble.",
        "dailyTip.1": "Bebe un vaso de agua nada más levantarte.",
        "dailyTip.2": "Los estiramientos suaves pueden aliviar la tensión de la espalda.",
        "dailyTip.3": "Un paseo corto después de comer puede ayudar a la digestión.",
        "dailyTip.4": "Ten snacks saludables a mano.",
        "dailyTip.5": "Practica la respiración profunda unos minutos.",
        "dailyTip.6": "Duerme del lado izquierdo cuando sea posible.",
        "dailyTip.7": "Anota preguntas para tu próxima cita prenatal.",
        "dailyTip.8": "Celebra los pequeños logros cada día.",
        "dailyTip.9": "Limita la cafeína y prioriza el descanso.",
        "dailyTip.10": "Conecta con tu persona de apoyo.",
        "dailyTip.11": "Los ejercicios del suelo pélvico favorecen la recuperación.",
        "dailyTip.12": "Come alimentos ricos en hierro como espinacas y lentejas.",
        "dailyTip.13": "Toma tu vitamina prenatal a diario.",
        "dailyTip.14": "Evita acostarte boca arriba después de la semana 20.",
        "dailyTip.15": "Controla tu ingesta de agua: intenta 8 vasos.",
        "dailyTip.16": "Usa zapatos cómodos y con buen soporte.",
        "dailyTip.17": "Un baño caliente puede aliviar molestias.",
        "dailyTip.18": "Prepara una pequeña bolsa para el hospital cuando se acerque la fecha.",
        "dailyTip.19": "Confía en tu instinto.",
        "dailyTip.20": "Escribe una cosa por la que estés agradecida.",
        "dailyTip.21": "Come comidas pequeñas si tienes náuseas.",
        "dailyTip.22": "Mantente activa con ejercicio seguro en el embarazo.",
        "dailyTip.23": "Hidrata tu barriga mientras crece.",
        "dailyTip.24": "Aprende a decir que no: descansar también es productivo.",
        "dailyTip.25": "Conoce los patrones de movimiento de tu bebé.",
        "dailyTip.26": "Prepara comidas congeladas para el posparto.",
        "dailyTip.27": "Infórmate sobre signos de parto para sentirte preparada.",
        "dailyTip.28": "Mantente fresca e hidratada en climas cálidos.",
        "dailyTip.29": "Pide ayuda cuando la necesites.",
        "dailyTip.30": "Disfruta esta etapa única.",
    },
    "fr": {
        "weekGuide.development %lld": "La semaine %lld apporte de nouveaux jalons de croissance. Les organes et systèmes de votre bébé continuent de se développer rapidement à ce stade de la grossesse.",
        "weekGuide.momFeeling %lld": "Vous pouvez remarquer des changements d'énergie et des sensations corporelles typiques de la semaine %lld. Écoutez votre corps et reposez-vous au besoin.",
        "weekGuide.tip": "Restez hydratée et mangez équilibré cette semaine. De petites collations fréquentes peuvent améliorer votre confort.",
        "weekGuide.appointment.firstPrenatal": "La première visite prénatale est souvent prévue autour des semaines 8 à 10",
        "weekGuide.appointment.nuchal": "Le dépistage de la clarté nucale peut être proposé vers la semaine 12",
        "weekGuide.appointment.anatomy": "L'échographie morphologique a généralement lieu vers la semaine 20",
        "weekGuide.appointment.glucose": "Le dépistage du diabète gestationnel est souvent recommandé entre les semaines 24 et 28",
        "weekGuide.appointment.thirdTrimester": "Les contrôles du troisième trimestre peuvent devenir plus fréquents",
        "weekGuide.appointment.weeklyVisits": "Les visites hebdomadaires commencent souvent vers la semaine 36",
        "dailyTip.fallback": "Reposez-vous quand vous en avez besoin — votre corps accomplit un travail remarquable.",
        "dailyTip.1": "Buvez un verre d'eau dès le matin.",
        "dailyTip.2": "Des étirements doux peuvent soulager les tensions dorsales.",
        "dailyTip.3": "Une courte marche après les repas peut aider la digestion.",
        "dailyTip.4": "Gardez des collations saines à portée de main.",
        "dailyTip.5": "Pratiquez la respiration profonde quelques minutes.",
        "dailyTip.6": "Dormez sur le côté gauche lorsque c'est possible.",
        "dailyTip.7": "Notez vos questions pour votre prochain rendez-vous prénatal.",
        "dailyTip.8": "Célébrez les petites victoires chaque jour.",
        "dailyTip.9": "Limitez la caféine et privilégiez le repos.",
        "dailyTip.10": "Restez en contact avec votre personne de soutien.",
        "dailyTip.11": "Les exercices du plancher pelvien favorisent la récupération.",
        "dailyTip.12": "Mangez des aliments riches en fer comme les épinards et les lentilles.",
        "dailyTip.13": "Prenez votre vitamine prénatale chaque jour.",
        "dailyTip.14": "Évitez de rester allongée sur le dos après la semaine 20.",
        "dailyTip.15": "Suivez votre consommation d'eau — visez 8 verres.",
        "dailyTip.16": "Portez des chaussures confortables et bien soutenues.",
        "dailyTip.17": "Un bain chaud peut apaiser les douleurs.",
        "dailyTip.18": "Préparez un petit sac pour l'hôpital à l'approche de la date prévue.",
        "dailyTip.19": "Faites confiance à votre intuition.",
        "dailyTip.20": "Notez une chose pour laquelle vous êtes reconnaissante.",
        "dailyTip.21": "Mangez de petits repas en cas de nausées.",
        "dailyTip.22": "Restez active avec des exercices adaptés à la grossesse.",
        "dailyTip.23": "Hydratez votre ventre pendant qu'il s'étire.",
        "dailyTip.24": "Apprenez à dire non — se reposer est productif.",
        "dailyTip.25": "Apprenez à connaître les mouvements de votre bébé.",
        "dailyTip.26": "Préparez des plats congelés pour le post-partum.",
        "dailyTip.27": "Renseignez-vous sur les signes du travail pour vous sentir prête.",
        "dailyTip.28": "Restez au frais et hydratée par temps chaud.",
        "dailyTip.29": "Demandez de l'aide quand vous en avez besoin.",
        "dailyTip.30": "Profitez de cette période unique.",
    },
    "de": {
        "weekGuide.development %lld": "Woche %lld bringt neue Wachstumsmeilensteine. Die Organe und Systeme Ihres Babys entwickeln sich in dieser Schwangerschaftsphase weiterhin rasch.",
        "weekGuide.momFeeling %lld": "Sie können veränderte Energie und Körperempfindungen bemerken, die für Woche %lld typisch sind. Hören Sie auf Ihren Körper und ruhen Sie sich aus, wenn nötig.",
        "weekGuide.tip": "Bleiben Sie diese Woche hydratisiert und essen Sie ausgewogen. Kleine, häufige Snacks können für mehr Wohlbefinden sorgen.",
        "weekGuide.appointment.firstPrenatal": "Der erste Vorsorgetermin wird oft für Woche 8–10 geplant",
        "weekGuide.appointment.nuchal": "Das Nackentransparenz-Screening kann um Woche 12 angeboten werden",
        "weekGuide.appointment.anatomy": "Der Feindiagnostik-Ultraschall findet typischerweise um Woche 20 statt",
        "weekGuide.appointment.glucose": "Ein Glukose-Screening wird oft für Woche 24–28 empfohlen",
        "weekGuide.appointment.thirdTrimester": "Kontrollen im dritten Trimester können häufiger werden",
        "weekGuide.appointment.weeklyVisits": "Wöchentliche Termine beginnen oft um Woche 36",
        "dailyTip.fallback": "Ruhen Sie sich aus, wenn Sie es brauchen — Ihr Körper leistet Erstaunliches.",
        "dailyTip.1": "Trinken Sie morgens als Erstes ein Glas Wasser.",
        "dailyTip.2": "Sanftes Dehnen kann Rückenspannungen lösen.",
        "dailyTip.3": "Ein kurzer Spaziergang nach dem Essen kann die Verdauung fördern.",
        "dailyTip.4": "Halten Sie gesunde Snacks griffbereit.",
        "dailyTip.5": "Atmen Sie einige Minuten tief durch.",
        "dailyTip.6": "Schlafen Sie wenn möglich auf der linken Seite.",
        "dailyTip.7": "Notieren Sie Fragen für Ihren nächsten Vorsorgetermin.",
        "dailyTip.8": "Feiern Sie jeden Tag kleine Erfolge.",
        "dailyTip.9": "Begrenzen Sie Koffein und priorisieren Sie Ruhe.",
        "dailyTip.10": "Bleiben Sie mit Ihrer Bezugsperson verbunden.",
        "dailyTip.11": "Beckenbodentraining unterstützt die Erholung.",
        "dailyTip.12": "Essen Sie eisenreiche Lebensmittel wie Spinat und Linsen.",
        "dailyTip.13": "Nehmen Sie täglich Ihr Schwangerschaftsvitamin.",
        "dailyTip.14": "Vermeiden Sie es, nach Woche 20 flach auf dem Rücken zu liegen.",
        "dailyTip.15": "Achten Sie auf Ihre Wasserzufuhr — streben Sie 8 Gläser an.",
        "dailyTip.16": "Tragen Sie bequeme, stützende Schuhe.",
        "dailyTip.17": "Ein warmes Bad kann Beschwerden lindern.",
        "dailyTip.18": "Packen Sie eine kleine Kliniktasche, wenn der Termin näher rückt.",
        "dailyTip.19": "Vertrauen Sie Ihrem Instinkt.",
        "dailyTip.20": "Notieren Sie eine Sache, für die Sie dankbar sind.",
        "dailyTip.21": "Essen Sie kleine Mahlzeiten bei Übelkeit.",
        "dailyTip.22": "Bleiben Sie mit schwangerschaftssicherer Bewegung aktiv.",
        "dailyTip.23": "Pflegen Sie Ihren Bauch, während er wächst.",
        "dailyTip.24": "Lernen Sie Nein zu sagen — Ruhe ist produktiv.",
        "dailyTip.25": "Lernen Sie die Bewegungsmuster Ihres Babys kennen.",
        "dailyTip.26": "Bereiten Sie Tiefkühlgerichte für die Wochenbettzeit vor.",
        "dailyTip.27": "Informieren Sie sich über Wehenzeichen, um vorbereitet zu sein.",
        "dailyTip.28": "Bleiben Sie bei warmem Wetter kühl und hydratisiert.",
        "dailyTip.29": "Bitten Sie um Hilfe, wenn Sie sie brauchen.",
        "dailyTip.30": "Genießen Sie diese besondere Zeit.",
    },
    "it": {
        "weekGuide.development %lld": "La settimana %lld porta nuovi traguardi di crescita. Gli organi e i sistemi del tuo bambino continuano a svilupparsi rapidamente in questa fase della gravidanza.",
        "weekGuide.momFeeling %lld": "Potresti notare cambiamenti di energia e sensazioni corporee tipiche della settimana %lld. Ascolta il tuo corpo e riposati quando serve.",
        "weekGuide.tip": "Resta idratata e mangia pasti equilibrati questa settimana. Spuntini piccoli e frequenti possono aiutare il tuo benessere.",
        "weekGuide.appointment.firstPrenatal": "La prima visita prenatale è spesso programmata tra le settimane 8 e 10",
        "weekGuide.appointment.nuchal": "Lo screening della translucenza nucale può essere offerto intorno alla settimana 12",
        "weekGuide.appointment.anatomy": "L'ecografia morfologica avviene tipicamente intorno alla settimana 20",
        "weekGuide.appointment.glucose": "Lo screening del glucosio è spesso consigliato tra le settimane 24 e 28",
        "weekGuide.appointment.thirdTrimester": "I controlli del terzo trimestre possono aumentare di frequenza",
        "weekGuide.appointment.weeklyVisits": "Le visite settimanali spesso iniziano intorno alla settimana 36",
        "dailyTip.fallback": "Riposa quando ne hai bisogno — il tuo corpo sta facendo un lavoro straordinario.",
        "dailyTip.1": "Bevi un bicchiere d'acqua appena sveglia.",
        "dailyTip.2": "Stretching delicato può alleviare la tensione alla schiena.",
        "dailyTip.3": "Una breve passeggiata dopo i pasti può aiutare la digestione.",
        "dailyTip.4": "Tieni a portata di mano spuntini salutari.",
        "dailyTip.5": "Pratica la respirazione profonda per qualche minuto.",
        "dailyTip.6": "Dormi sul lato sinistro quando possibile.",
        "dailyTip.7": "Annota le domande per la prossima visita prenatale.",
        "dailyTip.8": "Celebra ogni giorno piccole vittorie.",
        "dailyTip.9": "Limita la caffeina e dai priorità al riposo.",
        "dailyTip.10": "Resta in contatto con la tua persona di supporto.",
        "dailyTip.11": "Gli esercizi del pavimento pelvico favoriscono il recupero.",
        "dailyTip.12": "Mangia cibi ricchi di ferro come spinaci e lenticchie.",
        "dailyTip.13": "Prendi la vitamina prenatale ogni giorno.",
        "dailyTip.14": "Evita di sdraiarti supina dopo la settimana 20.",
        "dailyTip.15": "Monitora l'assunzione d'acqua — punta a 8 bicchieri.",
        "dailyTip.16": "Indossa scarpe comode e di supporto.",
        "dailyTip.17": "Un bagno caldo può alleviare i dolori.",
        "dailyTip.18": "Prepara una piccola borsa per l'ospedale avvicinandosi la data.",
        "dailyTip.19": "Fidati del tuo istinto.",
        "dailyTip.20": "Scrivi una cosa per cui sei grata.",
        "dailyTip.21": "Mangia pasti piccoli se hai nausea.",
        "dailyTip.22": "Resta attiva con esercizi sicuri in gravidanza.",
        "dailyTip.23": "Idrata la pancia mentre si allunga.",
        "dailyTip.24": "Impara a dire di no — riposare è produttivo.",
        "dailyTip.25": "Impara a conoscere i movimenti del tuo bambino.",
        "dailyTip.26": "Prepara pasti congelati per il post-parto.",
        "dailyTip.27": "Informati sui segni del travaglio per sentirti preparata.",
        "dailyTip.28": "Resta fresca e idratata con il caldo.",
        "dailyTip.29": "Chiedi aiuto quando ne hai bisogno.",
        "dailyTip.30": "Goditi questa stagione unica.",
    },
    "pt": {
        "weekGuide.development %lld": "A semana %lld traz novos marcos de crescimento. Os órgãos e sistemas do seu bebé continuam a desenvolver-se rapidamente nesta fase da gravidez.",
        "weekGuide.momFeeling %lld": "Pode notar mudanças de energia e sensações corporais típicas da semana %lld. Ouça o seu corpo e descanse quando precisar.",
        "weekGuide.tip": "Mantenha-se hidratada e faça refeições equilibradas esta semana. Lanches pequenos e frequentes podem ajudar no conforto.",
        "weekGuide.appointment.firstPrenatal": "A primeira consulta pré-natal costuma ser marcada entre as semanas 8 e 10",
        "weekGuide.appointment.nuchal": "O rastreio da translucência nucal pode ser oferecido por volta da semana 12",
        "weekGuide.appointment.anatomy": "A ecografia morfológica é normalmente feita por volta da semana 20",
        "weekGuide.appointment.glucose": "O rastreio de glucose é frequentemente recomendado entre as semanas 24 e 28",
        "weekGuide.appointment.thirdTrimester": "As consultas do terceiro trimestre podem aumentar em frequência",
        "weekGuide.appointment.weeklyVisits": "As visitas semanais costumam começar por volta da semana 36",
        "dailyTip.fallback": "Descanse quando precisar — o seu corpo está a fazer um trabalho incrível.",
        "dailyTip.1": "Beba um copo de água logo de manhã.",
        "dailyTip.2": "Alongamentos suaves podem aliviar a tensão nas costas.",
        "dailyTip.3": "Uma caminhada curta após as refeições pode ajudar a digestão.",
        "dailyTip.4": "Tenha lanches saudáveis por perto.",
        "dailyTip.5": "Pratique respiração profunda durante alguns minutos.",
        "dailyTip.6": "Durma de lado esquerdo quando possível.",
        "dailyTip.7": "Anote perguntas para a próxima consulta pré-natal.",
        "dailyTip.8": "Celebre pequenas vitórias todos os dias.",
        "dailyTip.9": "Limite a cafeína e priorize o descanso.",
        "dailyTip.10": "Conecte-se com a sua pessoa de apoio.",
        "dailyTip.11": "Exercícios do assoalho pélvico apoiam a recuperação.",
        "dailyTip.12": "Coma alimentos ricos em ferro como espinafres e lentilhas.",
        "dailyTip.13": "Tome a sua vitamina pré-natal diariamente.",
        "dailyTip.14": "Evite deitar-se de costas após a semana 20.",
        "dailyTip.15": "Acompanhe a ingestão de água — procure 8 copos.",
        "dailyTip.16": "Use sapatos confortáveis e com bom suporte.",
        "dailyTip.17": "Um banho quente pode aliviar dores.",
        "dailyTip.18": "Prepare uma pequena mala para o hospital à medida que a data se aproxima.",
        "dailyTip.19": "Confie nos seus instintos.",
        "dailyTip.20": "Registe uma coisa pela qual está grata.",
        "dailyTip.21": "Coma refeições pequenas se tiver náuseas.",
        "dailyTip.22": "Mantenha-se ativa com exercício seguro na gravidez.",
        "dailyTip.23": "Hidrate a barriga enquanto ela cresce.",
        "dailyTip.24": "Aprenda a dizer não — descansar é produtivo.",
        "dailyTip.25": "Conheça os padrões de movimento do seu bebé.",
        "dailyTip.26": "Prepare refeições congeladas para o pós-parto.",
        "dailyTip.27": "Informe-se sobre sinais de trabalho de parto para se sentir preparada.",
        "dailyTip.28": "Mantenha-se fresca e hidratada em tempo quente.",
        "dailyTip.29": "Peça ajuda quando precisar.",
        "dailyTip.30": "Aproveite esta fase única.",
    },
    "ar": {
        "weekGuide.development %lld": "الأسبوع %lld يجلب معالم نمو جديدة. تستمر أعضاء وجهاز طفلك في التطور بسرعة خلال هذه المرحلة من الحمل.",
        "weekGuide.momFeeling %lld": "قد تلاحظين تغيرات في مستوى الطاقة وإحساسات جسدية typique للأسبوع %lld. استمعي لجسمك وارتاحي عند الحاجة.",
        "weekGuide.tip": "حافظي على الترطيب وتناولي وجبات متوازنة هذا الأسبوع. الوجبات الخفيفة الصغيرة والمتكررة قد تساعد على الراحة.",
        "weekGuide.appointment.firstPrenatal": "غالباً ما يُحدَّد موعد الزيارة الأولى قبل الولادة حول الأسابيع 8–10",
        "weekGuide.appointment.nuchal": "قد يُعرَض فحص شفافية الرقبة حول الأسبوع 12",
        "weekGuide.appointment.anatomy": "عادةً ما يُجرى تصوير الموجات فوق الصوتية التشريحية حول الأسبوع 20",
        "weekGuide.appointment.glucose": "غالباً ما يُوصى بفحص الجلوكوز حول الأسابيع 24–28",
        "weekGuide.appointment.thirdTrimester": "قد تزداد زيارات الفحص في الثلث الثالث",
        "weekGuide.appointment.weeklyVisits": "غالباً ما تبدأ الزيارات الأسبوعية حول الأسبوع 36",
        "dailyTip.fallback": "ارتاحي عندما تحتاجين — جسمك يقوم بعمل مذهل.",
        "dailyTip.1": "اشربي كوب ماء أول شيء في الصباح.",
        "dailyTip.2": "التمدد اللطيف قد يخفف توتر الظهر.",
        "dailyTip.3": "المشي القصير بعد الوجبات قد يساعد على الهضم.",
        "dailyTip.4": "احتفظي بوجبات خفيفة صحية قريبة.",
        "dailyTip.5": "مارسي التنفس العميق لبضع دقائق.",
        "dailyTip.6": "نامي على جانبك الأيسر عندما يكون ذلك ممكناً.",
        "dailyTip.7": "دوِّني أسئلة لموعدك القادم قبل الولادة.",
        "dailyTip.8": "احتفلي بالإنجازات الصغيرة كل يوم.",
        "dailyTip.9": "قللي الكافيين وأعطي الأولوية للراحة.",
        "dailyTip.10": "تواصلي مع شخص الدعم لديك.",
        "dailyTip.11": "تمارين قاع الحوض تدعم التعافي.",
        "dailyTip.12": "تناولي أطعمة غنية بالحديد مثل السبانخ والعدس.",
        "dailyTip.13": "تناولي فيتامين ما قبل الولادة يومياً.",
        "dailyTip.14": "تجنبي الاستلقاء على ظهرك بعد الأسبوع 20.",
        "dailyTip.15": "تتبعي شرب الماء — استهدفي 8 أكواب.",
        "dailyTip.16": "ارتدي أحذية مريحة وداعمة.",
        "dailyTip.17": "حمام دافئ قد يخفف الآلام.",
        "dailyTip.18": "جهّزي حقيبة مستشفى صغيرة مع اقتراب موعد الولادة.",
        "dailyTip.19": "ثقي بحدسك.",
        "dailyTip.20": "دوِّني شيئاً واحداً تشكرين عليه.",
        "dailyTip.21": "تناولي وجبات صغيرة إذا كان لديك غثيان.",
        "dailyTip.22": "ابقَ نشطة بتمارين آمنة أثناء الحمل.",
        "dailyTip.23": "رطّبي بطنك أثناء تمدده.",
        "dailyTip.24": "تعلّمي قول لا — الراحة منتجة.",
        "dailyTip.25": "تعرّفي على أنماط حركة طفلك.",
        "dailyTip.26": "حضّري وجبات مجمدة لفترة ما بعد الولادة.",
        "dailyTip.27": "اقرئي عن علامات المخاض لتشعري بالاستعداد.",
        "dailyTip.28": "ابقَ باردة ومرطبة في الطقس الحار.",
        "dailyTip.29": "اطلبي المساعدة عندما تحتاجين.",
        "dailyTip.30": "استمتعي بهذا الموسم الفريد.",
    },
    "hi": {
        "weekGuide.development %lld": "सप्ताह %lld नए विकास के मील के पत्थर लाता है। गर्भावस्था के इस चरण में आपके बच्चे के अंग और तंत्र तेज़ी से विकसित होते रहते हैं।",
        "weekGuide.momFeeling %lld": "आप सप्ताह %lld के लिए typique ऊर्जा स्तर और शारीरिक संवेदनाएँ महसूस कर सकती हैं। अपने शरीर की सुनें और जरूरत पड़ने पर आराम करें।",
        "weekGuide.tip": "इस सप्ताह हाइड्रेटेड रहें और संतुलित भोजन करें। छोटे, बार-बार स्नैक्स आराम में मदद कर सकते हैं।",
        "weekGuide.appointment.firstPrenatal": "पहली प्रसवपूर्व जांच अक्सर 8–10 सप्ताह के आसपास निर्धारित होती है",
        "weekGuide.appointment.nuchal": "न्यूकल ट्रांसलूसेंसी स्क्रीनिंग सप्ताह 12 के आसपास offered हो सकती है",
        "weekGuide.appointment.anatomy": "एनाटॉमी अल्ट्रासाउंड आमतौर पर सप्ताह 20 के आसपास होता है",
        "weekGuide.appointment.glucose": "ग्लूकोज स्क्रीनिंग अक्सर 24–28 सप्ताह के आसपास recommended होती है",
        "weekGuide.appointment.thirdTrimester": "तीसरी तिमाही की जांच अधिक बार हो सकती है",
        "weekGuide.appointment.weeklyVisits": "साप्ताहिक मुलाकातें अक्सर सप्ताह 36 के आसपास शुरू होती हैं",
        "dailyTip.fallback": "जब जरूरत हो आराम करें — आपका शरीर अद्भुत काम कर रहा है।",
        "dailyTip.1": "सुबह उठते ही एक गिलास पानी पिएं।",
        "dailyTip.2": "हल्का स्टretching पीठ के तनाव को कम कर सकता है।",
        "dailyTip.3": "भोजन के बाद छोटी सैर पाचन में मदद कर सकती है।",
        "dailyTip.4": "स्वस्थ स्नैक्स पास रखें।",
        "dailyTip.5": "कुछ मिनट गहरी साँस लें।",
        "dailyTip.6": "जब संभव हो बाएँ तरफ सोएं।",
        "dailyTip.7": "अगली प्रसवपूर्व मुलाकात के लिए सवाल लिखें।",
        "dailyTip.8": "हर दिन छोटी जीत का जश्न मनाएँ।",
        "dailyTip.9": "कैफीन सीमित करें और आराम को प्राथमिकता दें।",
        "dailyTip.10": "अपने सहयोगी से जुड़ें।",
        "dailyTip.11": "पेल्विक फ्लोर व्यायाम रिकवरी में मदद करते हैं।",
        "dailyTip.12": "पालक और दाल जैसे आयरन युक्त खाद्य पदार्थ खाएँ।",
        "dailyTip.13": "प्रसवपूर्व विटामिन रोज़ लें।",
        "dailyTip.14": "सप्ताह 20 के बाद पीठ के बल लेटने से बचें।",
        "dailyTip.15": "पानी का सेवन ट्रैक करें — 8 गिलास का लक्ष्य रखें।",
        "dailyTip.16": "आरामदायक, सहारा देने वाले जूते पहनें।",
        "dailyTip.17": "गर्म स्नान दर्द को शांत कर सकता है।",
        "dailyTip.18": "ड्यू डेट नज़दीक आने पर छोटा अस्पताल बैग पैक करें।",
        "dailyTip.19": "अपनी अंतर्दृष्टि पर भरोसा करें।",
        "dailyTip.20": "एक चीज़ लिखें जिसके लिए आप आभारी हैं।",
        "dailyTip.21": "मतली हो तो छोटे भोजन करें।",
        "dailyTip.22": "गर्भावस्था-सुरक्षित व्यायाम से सक्रिय रहें।",
        "dailyTip.23": "पेट खिंचते समय मॉइस्चराइज़ करें।",
        "dailyTip.24": "ना कहना सीखें — आराम उत्पादक है।",
        "dailyTip.25": "बच्चे की हलचल के पैटर्न जानें।",
        "dailyTip.26": "पोस्टपार्टम के लिए फ्रीज़र भोजन तैयार करें।",
        "dailyTip.27": "प्रसव के संकेत पढ़ें ताकि तैयार महसूस करें।",
        "dailyTip.28": "गर्म मौसम में ठंडे और हाइड्रेटेड रहें।",
        "dailyTip.29": "जरूरत पड़ne पर मदद माँगें।",
        "dailyTip.30": "इस अनोखे समय का आनंद लें।",
    },
    "bn": {
        "weekGuide.development %lld": "সপ্তাহ %lld নতুন বৃদ্ধির মাইলফলক নিয়ে আসে। গর্ভাবস্থার এই পর্যায়ে আপনার শিশুর অঙ্গ-প্রতঙ্গ ও সিস্টেম দ্রুত গড়ে উঠতে থাকে।",
        "weekGuide.momFeeling %lld": "সপ্তাহ %lld-এর জন্য সাধারণ শক্তির পরিবর্তন ও শারীরিক অনুভূতি লক্ষ করতে পারেন। শরীরের কথা শুনুন এবং প্রয়োজনে বিশ্রাম নিন।",
        "weekGuide.tip": "এই সপ্তাহে হাইড্রেটেড থাকুন এবং সুষম খাবার খান। ছোট, ঘন ঘন স্ন্যাকস আরামে সাহায্য করতে পারে।",
        "weekGuide.appointment.firstPrenatal": "প্রথম প্রসবপূর্ব সাক্ষাৎ প্রায় ৮–১০ সপ্তাহে নির্ধারিত হয়",
        "weekGuide.appointment.nuchal": "নুকাল ট্রান্সলুসেন্সি স্ক্রিনিং সপ্তাহ ১২-এর আশেপাশে দেওয়া হতে পারে",
        "weekGuide.appointment.anatomy": "অ্যানাটমি আল্ট্রাসাউন্ড সাধারণত সপ্তাহ ২০-এর আশেপাশে হয়",
        "weekGuide.appointment.glucose": "গ্লুকোজ স্ক্রিনিং প্রায় ২৪–২৮ সপ্তাহে সুপারিশ করা হয়",
        "weekGuide.appointment.thirdTrimester": "তৃতীয় তিমাহির পরীক্ষা আরও ঘন ঘন হতে পারে",
        "weekGuide.appointment.weeklyVisits": "সাপ্তাহিক সাক্ষাৎ প্রায় সপ্তাহ ৩৬-এ শুরু হয়",
        "dailyTip.fallback": "প্রয়োজন হলে বিশ্রাম নিন — আপনার শরীর অসাধারণ কাজ করছে।",
        "dailyTip.1": "সকালে উঠেই এক গ্লাস পানি পান করুন।",
        "dailyTip.2": "হালকা স্ট্রেচিং পিঠের টান কমাতে পারে।",
        "dailyTip.3": "খাবারের পর ছোট হাঁটা হজমে সাহায্য করতে পারে।",
        "dailyTip.4": "স্বাস্থ্যকর স্ন্যাকস কাছে রাখুন।",
        "dailyTip.5": "কয়েক মিনিট গভীর শ্বাস নিন।",
        "dailyTip.6": "সম্ভব হলে বাম পাশে ঘুমান।",
        "dailyTip.7": "পরবর্তী প্রসবপূর্ব সাক্ষাতের জন্য প্রশ্ন লিখে রাখুন।",
        "dailyTip.8": "প্রতিদিন ছোট ছোট জয় উদযাপন করুন।",
        "dailyTip.9": "ক্যাফেইন সীমিত করুন এবং বিশ্রামকে অগ্রাধিকার দিন।",
        "dailyTip.10": "আপনার সহায়ক ব্যক্তির সাথে যোগাযোগ রাখুন।",
        "dailyTip.11": "পেলভিক ফ্লোর ব্যায়াম পুনরুদ্ধারে সাহায্য করে।",
        "dailyTip.12": "পালং শাক ও মসুর ডালের মতো লৌহ সমৃদ্ধ খাবার খান।",
        "dailyTip.13": "প্রতিদিন প্রসবপূর্ব ভিটামিন নিন।",
        "dailyTip.14": "২০ সপ্তাহের পর পিঠের বালিশে শুয়ে থাকা এড়িয়ে চলুন।",
        "dailyTip.15": "পানি গ্রহণ ট্র্যাক করুন — ৮ গ্লাস লক্ষ্য রাখুন।",
        "dailyTip.16": "আরামদায়ক, সহায়ক জুতা পরুন।",
        "dailyTip.17": "গরম স্নান ব্যথা কমাতে পারে।",
        "dailyTip.18": "ডিউ ডেটের কাছাকাছি ছোট হাসপাতালের ব্যাগ প্যাক করুন।",
        "dailyTip.19": "আপনার অনুভূতির ওপর বিশ্বাস রাখুন।",
        "dailyTip.20": "যার জন্য কৃতজ্ঞ তা একটা জিনিস লিখুন।",
        "dailyTip.21": "বমি বমি ভাব থাকলে ছোট খাবার খান।",
        "dailyTip.22": "গর্ভাবস্থা-নিরাপদ ব্যায়ামে সক্রিয় থাকুন।",
        "dailyTip.23": "পেট প্রসারিত হওয়ার সাথে ময়েশ্চারাইজ করুন।",
        "dailyTip.24": "না বলতে শিখুন — বিশ্রামও উৎপাদনশীল।",
        "dailyTip.25": "শিশুর নড়াচড়ার ধরন শিখুন।",
        "dailyTip.26": "পোস্টpartum-এর জন্য ফ্রিজার মিল প্রস্তুত করুন।",
        "dailyTip.27": "প্রসবের লক্ষণ সম্পর্কে পড়ুন যাতে প্রস্তুত থাকেন।",
        "dailyTip.28": "গরম আবহাওয়ায় ঠান্ডা ও হাইড্রেটেড থাকুন।",
        "dailyTip.29": "প্রয়োজন হলে সাহায্য চান।",
        "dailyTip.30": "এই অনন্য সময় উপভোগ করুন।",
    },
}

def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for lang, data in T.items():
        path = OUT / f"{lang}.json"
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {path.name} ({len(data)} keys)")

if __name__ == "__main__":
    main()
