# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "Αραβικά", "bengali": "Βεγγαλικά", "chinese": "Κινεζικά", "dutch": "Ολλανδικά",
    "english": "Αγγλικά", "french": "Γαλλικά", "german": "Γερμανικά", "greek": "Ελληνικά",
    "hebrew": "Εβραϊκά", "hindi": "Χίντι", "indonesian": "Ινδονησιακά", "italian": "Ιταλικά",
    "japanese": "Ιαπωνικά", "korean": "Κορεατικά", "malay": "Μαλαϊκά", "polish": "Πολωνικά",
    "portuguese": "Πορτογαλικά", "romanian": "Ρουμανικά", "russian": "Ρωσικά",
    "spanish": "Ισπανικά", "swedish": "Σουηδικά", "thai": "Ταϊλανδικά", "turkish": "Τουρκικά",
    "ukrainian": "Ουκρανικά", "vietnamese": "Βιετναμικά",
}
TABLE = {
    "Enter a weight between %@ and %@.": "Εισαγάγετε βάρος μεταξύ %1$@ και %2$@.",
    "Step %lld of %lld": "Βήμα %1$lld από %2$lld",
    "Share with Partner": "Κοινοποίηση στον/στην σύντροφο",
    "Camera": "Κάμερα",
    "Add your first photo to start your visual journal.": "Προσθέστε την πρώτη σας φωτογραφία για να ξεκινήσετε το οπτικό ημερολόγιο.",
    "No bump photos yet": "Δεν υπάρχουν ακόμα φωτογραφίες κοιλιάς",
    "Optional note": "Προαιρετική σημείωση",
    "Photo Library": "Βιβλιοθήκη φωτογραφιών",
    "Save Photo": "Αποθήκευση φωτογραφίας",
    "Capture your growing bump each week and watch your journey unfold.": "Καταγράψτε την αυξανόμενη κοιλιά σας κάθε εβδομάδα και παρακολουθήστε το ταξίδι σας.",
    "Week %lld Bump": "Κοιλιά εβδομάδας %lld",
    "Back": "Πίσω", "Cancel": "Ακύρωση", "Continue": "Συνέχεια", "Date": "Ημερομηνία",
    "Done!": "Έγινε!", "Gender": "Φύλο", "History": "Ιστορικό", "Letter": "Γράμμα",
    "Log": "Καταχώρηση", "Logged": "Καταχωρήθηκε", "ongoing": "σε εξέλιξη",
    "(optional)": "(προαιρετικό)", "Pause": "Παύση",
    "%@ is part of Bloomly Plus": "Το %@ αποτελεί μέρος του Bloomly Plus",
    "Reset": "Επαναφορά", "Save": "Αποθήκευση", "Severity": "Σοβαρότητα",
    "Start": "Έναρξη", "Style": "Στυλ", "Upgrade": "Αναβάθμιση", "Week %lld": "Εβδομάδα %lld",
    "Period ended": "Η περίοδος τελείωσε", "Day Summary": "Σύνοψη ημέρας", "Notes": "Σημειώσεις",
    "Daily Log": "Ημερήσιο ημερολόγιο", "Daily goal: 8 glasses": "Ημερήσιος στόχος: 8 ποτήρια",
    "Daily Tip": "Ημερήσια συμβουλή", "%lld days until due date": "%lld ημέρες μέχρι την ημερομηνία τοκετού",
    "Your due date has passed": "Η ημερομηνία τοκετού έχει περάσει", "glasses of water": "ποτήρια νερό",
    "How are you feeling?": "Πώς αισθάνεστε;", "Mood": "Διάθεση", "Planning Mode": "Λειτουργία σχεδιασμού",
    "Track your cycle and prepare for your journey.": "Παρακολουθήστε τον κύκλο σας και ετοιμαστείτε για το ταξίδι.",
    "Pregnancy Progress": "Πρόοδος εγκυμοσύνης", "Quick Log": "Γρήγορη καταχώρηση",
    "Symptoms": "Συμπτώματα", "Home": "Αρχική", "Water": "Νερό", "Water Intake": "Πρόσληψη νερού",
    "Week %lld of 40": "Εβδομάδα %lld από 40", "Weight": "Βάρος",
    "Due date": "Ημερομηνία τοκετού", "Last period": "Τελευταία περίοδος",
    "Last period start": "Έναρξη τελευταίας περιόδου", "Last menstrual period": "Τελευταία εμμηνορροϊά",
    "When did your last period start? You can log more dates anytime.": "Πότε ξεκίνησε η τελευταία σας περίοδος; Μπορείτε να καταγράψετε περισσότερες ημερομηνίες ανά πάσα στιγμή.",
    "Cycle insights appear on your Home tab": "Οι πληροφορίες κύκλου εμφανίζονται στην καρτέλα Αρχική",
    "Track your cycle": "Παρακολουθήστε τον κύκλο σας",
    "We'll calculate your week and due date.": "Θα υπολογίσουμε την εβδομάδα και την ημερομηνία τοκετού.",
    "When did your journey begin?": "Πότε ξεκίνησε το ταξίδι σας;",
    "Baby size, tips & milestones": "Μέγεθος μωρού, συμβουλές και ορόσημα",
    "Week-by-week guides": "Οδηγοί ανά εβδομάδα",
    "Symptoms, mood, water & more": "Συμπτώματα, διάθεση, νερό και άλλα",
    "Daily wellness logging": "Ημερήσια καταγραφή ευεξίας",
    "Your data never leaves your phone": "Τα δεδομένα σας δεν φεύγουν ποτέ από το τηλέφωνό σας",
    "100% on your device": "100% στη συσκευή σας", "Get Started": "Ξεκινήστε",
    "Cycle tracking, fertile windows & prep": "Παρακολούθηση κύκλου, γόνιμα παράθυρα και προετοιμασία",
    "I'm planning": "Σχεδιάζω",
    "Track weeks, baby size, kicks & milestones": "Παρακολουθήστε εβδομάδες, μέγεθος μωρού, κλωτσιές και ορόσημα",
    "I'm pregnant": "Είμαι έγκυος",
    "We'll tailor Bloomly to your stage.": "Θα προσαρμόσουμε το Bloomly στο στάδιό σας.",
    "What brings you here?": "Τι σας φέρνει εδώ;", "Daily reminders": "Ημερήσιες υπενθυμίσεις",
    "First pregnancy?": "Πρώτη εγκυμοσύνη;",
    "This is my first pregnancy": "Αυτή είναι η πρώτη μου εγκυμοσύνη",
    "We'll ask for notification permission when you finish setup.": "Θα ζητήσουμε άδεια ειδοποιήσεων όταν ολοκληρώσετε τη ρύθμιση.",
    "Starting weight": "Αρχικό βάρος",
    "Pre-pregnancy weight helps track healthy gain over time.": "Το βάρος πριν την εγκυμοσύνη βοηθά στην παρακολούθηση υγιούς αύξησης.",
    "A few quick preferences to personalize Bloomly.": "Μερικές γρήγορες προτιμήσεις για εξατομίκευση του Bloomly.",
    "Almost there!": "Σχεδόν έτοιμοι!", "Weight unit": "Μονάδα βάρους",
    "Key dates": "Βασικές ημερομηνίες", "Your journey": "Το ταξίδι σας",
    "Preferences": "Προτιμήσεις", "Welcome": "Καλώς ήρθατε",
    "A calm, private space to track every moment — from first flutter to final countdown.": "Ένας ήρεμος, ιδιωτικός χώρος για κάθε στιγμή — από το πρώτο φτερούγισμα μέχρι την τελική αντίστροφη μέτρηση.",
    "Your journey starts here": "Το ταξίδι σας ξεκινά εδώ",
    "Due date has passed — any day now!": "Η ημερομηνία τοκετού πέρασε — οποιαδήποτε στιγμή!",
    "— For %@": "— Για %@", "Can't wait to meet our little one!": "Ανυπομονώ να γνωρίσουμε το μικρό μας!",
    "Personal message": "Προσωπικό μήνυμα", "Share Image": "Κοινοποίηση εικόνας",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — Εβδομάδα %lld",
    "Bloomly Week %lld": "Bloomly Εβδομάδα %lld",
    "Share Text Update": "Κοινοποίηση κειμένου", "Share Update": "Κοινοποίηση ενημέρωσης",
    "Appointments with reminders": "Ραντεβού με υπενθυμίσεις",
    "Trimester-aware nutrition guide": "Οδηγός διατροφής ανά τρίμηνο",
    "Statistics & history charts": "Στατιστικά και γραφήματα ιστορικού",
    "Full symptom & weight logging": "Πλήρης καταγραφή συμπτωμάτων και βάρους",
    "Wellness tools: Kegel, kick & contraction timers": "Εργαλεία ευεξίας: Kegel, κλωτσιές και χρονόμετρο συσπάσεων",
    "Purchase could not be completed.": "Η αγορά δεν ολοκληρώθηκε.",
    "Restore Purchases": "Επαναφορά αγορών", "Start Free": "Δωρεάν έναρξη",
    "Subscriptions will appear when configured in App Store Connect.": "Οι συνδρομές θα εμφανιστούν όταν ρυθμιστούν στο App Store Connect.",
    "Unlock the full wellness experience": "Ξεκλειδώστε την πλήρη εμπειρία ευεξίας",
    "Account": "Λογαριασμός", "Appointments": "Ραντεβού", "Baby Names": "Ονόματα μωρού",
    "Bump Journal": "Ημερολόγιο κοιλιάς", "Cycle Tracker": "Παρακολούθηση κύκλου",
    "Daily Reminders": "Ημερήσιες υπενθυμίσεις", "Due Date": "Ημερομηνία τοκετού",
    "Favorites": "Αγαπημένα", "Features": "Λειτουργίες", "Free": "Δωρεάν",
    "Log Period": "Καταγραφή περιόδου", "Mode": "Λειτουργία", "New Appointment": "Νέο ραντεβού",
    "No upcoming appointments": "Δεν υπάρχουν επερχόμενα ραντεβού",
    "Nutrition Guide": "Οδηγός διατροφής",
    "Used when sharing weekly baby-size updates.": "Χρησιμοποιείται κατά την κοινοποίηση εβδομαδιαίων ενημερώσεων.",
    "Partner's name (optional)": "Όνομα συντρόφου (προαιρετικό)",
    "Partner Sharing": "Κοινοποίηση με σύντροφο", "Past": "Παρελθόν", "Planning": "Σχεδιασμός",
    "Pregnant": "Έγκυος", "Premium": "Πρεμιουμ", "Privacy": "Απόρρητο",
    "Bloomly stores all your data exclusively on your device.": "Το Bloomly αποθηκεύει όλα τα δεδομένα σας αποκλειστικά στη συσκευή σας.",
    "Collect any personal data": "Συλλέγουμε προσωπικά δεδομένα",
    "Send data to servers or the cloud": "Στέλνουμε δεδομένα σε διακομιστές ή cloud",
    "Use analytics or tracking SDKs": "Χρησιμοποιούμε analytics ή tracking SDK",
    "Show advertisements": "Εμφανίζουμε διαφημίσεις",
    "Require an account or login": "Απαιτούμε λογαριασμό ή σύνδεση",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "Τα δεδομένα σας δεν φεύγουν από το iPhone σας, εκτός αν κάνετε backup μέσω iCloud ή iTunes.",
    "Your Privacy Matters": "Το απόρρητό σας έχει σημασία", "We do not:": "Δεν:",
    "Settings": "Ρυθμίσεις", "Statistics": "Στατιστικά", "Profile": "Προφίλ",
    "Upcoming": "Επερχόμενα", "Upgrade to Bloomly Plus": "Αναβάθμιση σε Bloomly Plus",
    "Week": "Εβδομάδα", "Weight Tracker": "Παρακολούθηση βάρους",
    "Your name (optional)": "Το όνομά σας (προαιρετικό)",
    "Breakfast": "Πρωινό", "Dinner": "Βραδινό",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "Ημερήσιες τοπικές υπενθυμίσεις για ενυδάτωση και διατροφή.",
    "Lunch": "Μεσημεριανό", "Meal Reminders": "Υπενθυμίσεις γευμάτων",
    "Meal Schedule": "Πρόγραμμα γευμάτων",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "Οι ειδοποιήσεις είναι απενεργοποιημένες. Πατήστε εδώ για Ρυθμίσεις.",
    "Snack": "Σνακ", "Water Reminders": "Υπενθυμίσεις νερού", "Water Schedule": "Πρόγραμμα νερού",
    "Appearance": "Εμφάνιση", "Choose a color theme for your app": "Επιλέξτε χρωματικό θέμα για την εφαρμογή",
    "Language": "Γλώσσα",
    "Content like week guides will stay in English until translated.": "Περιεχόμενο όπως οι εβδομαδιαίοι οδηγοί θα παραμείνει στα Αγγλικά μέχρι να μεταφραστεί.",
    "Your pregnancy companion": "Ο σύντροφός σας στην εγκυμοσύνη",
    "Best": "Καλύτερο", "Current": "Τρέχον", "Details": "Λεπτομέρειες",
    "Fertile Window": "Γόνιμο παράθυρο", "Gain": "Αύξηση", "Mood History": "Ιστορικό διάθεσης",
    "Next Period": "Επόμενη περίοδος", "No symptom data yet": "Δεν υπάρχουν ακόμα δεδομένα συμπτωμάτων",
    "No weight data yet. Log from Home or Weight Tracker.": "Δεν υπάρχουν ακόμα δεδομένα βάρους. Καταγράψτε από Αρχική ή Παρακολούθηση βάρους.",
    "Ovulation Estimate": "Εκτίμηση ωορρηξίας", "Prediction": "Πρόβλεψη",
    "Symptom Frequency": "Συχνότητα συμπτωμάτων", "Water Streak": "Σειρά νερού",
    "Weight Over Time": "Βάρος στο χρόνο", "Tools": "Εργαλεία", "Week Guide": "Οδηγός εβδομάδας",
    "Blush": "Ροζ", "Coral": "Κοράλλι", "Dark": "Σκούρο", "Forest": "Δάσος",
    "Lavender": "Λεβάντα", "Midnight": "Μεσάνυχτα", "Mint": "Μέντα", "Peach": "Ροδάκινο",
    "Rain": "Βροχή", "Rose Gold": "Ροζ χρυσό", "Sunset": "Ηλιοβασίλεμα", "White": "Λευκό",
    "Duration: %@": "Διάρκεια: %@", "Interval: %@": "Διάστημα: %@",
    "Start Contraction": "Έναρξη συσπάσεως", "Stop Contraction": "Διακοπή συσπάσεως",
    "Time contractions": "Χρονομέτρηση συσπάσεων", "Contraction Timer": "Χρονόμετρο συσπάσεων",
    "Hydration": "Ενυδάτωση",
    "Log water from the Home tab quick actions": "Καταγράψτε νερό από τις γρήγορες ενέργειες στην Αρχική",
    "Visual water counter": "Οπτικός μετρητής νερού", "Complete!": "Ολοκληρώθηκε!",
    "Hold": "Κράτημα", "Hold for 5 seconds, release for 5 seconds": "Κρατήστε 5 δευτερόλεπτα, αφήστε 5 δευτερόλεπτα",
    "Ready": "Έτοιμο", "Release": "Αφήστε", "Rep %lld of 10": "Επανάληψη %lld από 10",
    "Rest": "Ξεκούραση", "Set %lld of 3": "Σετ %lld από 3", "3 sets × 10 reps": "3 σετ × 10 επαναλήψεις",
    "Kegel Timer": "Χρονόμετρο Kegel", "kicks": "κλωτσιές",
    "Save Session": "Αποθήκευση συνεδρίας", "Tap for Kick": "Πατήστε για κλωτσιά",
    "Kick Counter": "Μετρητής κλωτσιών", "Track baby movements": "Παρακολούθηση κινήσεων μωρού",
    "Log weight & view trends": "Καταγραφή βάρους και τάσεις", "Wellness tools": "Εργαλεία ευεξίας",
    "Appointment": "Ραντεβού", "Development": "Ανάπτυξη", "Length": "Μήκος",
    "How You May Feel": "Πώς μπορεί να νιώθετε", "Tip": "Συμβουλή",
    "Week %lld Guidance": "Οδηγία εβδομάδας %lld",
    "Your weight entries will appear here.": "Οι καταχωρήσεις βάρους θα εμφανιστούν εδώ.",
    "Invalid Weight": "Μη έγκυρο βάρος",
    "Please enter a valid weight in %@.": "Εισαγάγετε έγκυρο βάρος σε %@.",
    "Latest": "Τελευταίο", "Log Weight": "Καταγραφή βάρους",
    "Not logged yet": "Δεν έχει καταχωρηθεί ακόμα",
    "No weight logged yet": "Δεν έχει καταχωρηθεί βάρος ακόμα",
    "Or enter manually": "Ή εισαγάγετε χειροκίνητα", "Pre-pregnancy": "Πριν την εγκυμοσύνη",
    "Previous entry": "Προηγούμενη καταχώρηση", "Set": "Ορισμός", "Since Last": "Από την τελευταία",
    "%@ since last entry": "%@ από την τελευταία καταχώρηση",
    "Since starting weight": "Από το αρχικό βάρος",
    "%@ since starting weight": "%@ από το αρχικό βάρος", "Starting": "Αρχικό",
    "Your pre-pregnancy weight helps track healthy gain over time.": "Το βάρος πριν την εγκυμοσύνη βοηθά στην παρακολούθηση υγιούς αύξησης.",
    "Starting Weight": "Αρχικό βάρος",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "Συμβουλή: ορίστε το αρχικό βάρος στην Παρακολούθηση βάρους.",
    "Tap to add": "Πατήστε για προσθήκη", "Total Change": "Συνολική αλλαγή",
    "Weight Trend": "Τάση βάρους",
}
