# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "ערבית", "bengali": "בנגלית", "chinese": "סינית", "dutch": "הולנדית",
    "english": "אנגלית", "french": "צרפתית", "german": "גרמנית", "greek": "יוונית",
    "hebrew": "עברית", "hindi": "הינדי", "indonesian": "אינדונזית", "italian": "איטלקית",
    "japanese": "יפנית", "korean": "קוריאנית", "malay": "מלאית", "polish": "פולנית",
    "portuguese": "פורטוגזית", "romanian": "רומנית", "russian": "רוסית",
    "spanish": "ספרדית", "swedish": "שוודית", "thai": "תאילנדית", "turkish": "טורקית",
    "ukrainian": "אוקראינית", "vietnamese": "וייטנאמית",
}
TABLE = {
    "Enter a weight between %@ and %@.": "הזיני משקל בין %1$@ ל-%2$@.",
    "Step %lld of %lld": "שלב %1$lld מתוך %2$lld",
    "Share with Partner": "שיתוף עם בן/בת הזוג",
    "Camera": "מצלמה",
    "Add your first photo to start your visual journal.": "הוסיפי את התמונה הראשונה כדי להתחיל את יומן ההריון.",
    "No bump photos yet": "עדיין אין תמונות בטן",
    "Optional note": "הערה (אופציונלי)",
    "Photo Library": "ספריית תמונות",
    "Save Photo": "שמירת תמונה",
    "Capture your growing bump each week and watch your journey unfold.": "צלמי את הבטן הגדלה מדי שבוע ועקבי אחרי המסע שלך.",
    "Week %lld Bump": "בטן שבוע %lld",
    "Back": "חזרה", "Cancel": "ביטול", "Continue": "המשך", "Date": "תאריך",
    "Done!": "סיימת!", "Gender": "מין", "History": "היסטוריה", "Letter": "אות",
    "Log": "רישום", "Logged": "נרשם", "ongoing": "בתהליך",
    "(optional)": "(אופציונלי)", "Pause": "השהיה",
    "%@ is part of Bloomly Plus": "%@ הוא חלק מ-Bloomly Plus",
    "Reset": "איפוס", "Save": "שמירה", "Severity": "חומרה",
    "Start": "התחלה", "Style": "סגנון", "Upgrade": "שדרוג", "Week %lld": "שבוע %lld",
    "Period ended": "הווסת הסתיימה", "Day Summary": "סיכום יום", "Notes": "הערות",
    "Daily Log": "יומן יומי", "Daily goal: 8 glasses": "יעד יומי: 8 כוסות",
    "Daily Tip": "טיפ יומי", "%lld days until due date": "%lld ימים עד מועד הלידה",
    "Your due date has passed": "מועד הלידה עבר", "glasses of water": "כוסות מים",
    "How are you feeling?": "איך את מרגישה?", "Mood": "מצב רוח", "Planning Mode": "מצב תכנון",
    "Track your cycle and prepare for your journey.": "עקבי אחרי המחזור והתכוני למסע.",
    "Pregnancy Progress": "התקדמות ההריון", "Quick Log": "רישום מהיר",
    "Symptoms": "תסמינים", "Home": "בית", "Water": "מים", "Water Intake": "צריכת מים",
    "Week %lld of 40": "שבוע %lld מתוך 40", "Weight": "משקל",
    "Due date": "מועד לידה", "Last period": "ווסת אחרונה",
    "Last period start": "תחילת ווסת אחרונה", "Last menstrual period": "ווסת אחרונה",
    "When did your last period start? You can log more dates anytime.": "מתי התחילה הווסת האחרונה? אפשר לרשום תאריכים נוספים בכל עת.",
    "Cycle insights appear on your Home tab": "תובנות מחזור מופיעות בלשונית הבית",
    "Track your cycle": "עקבי אחרי המחזור",
    "We'll calculate your week and due date.": "נחשב את השבוע ומועד הלידה.",
    "When did your journey begin?": "מתי המסע שלך התחיל?",
    "Baby size, tips & milestones": "גודל תינוק, טיפים ואבני דרך",
    "Week-by-week guides": "מדריכים שבועיים",
    "Symptoms, mood, water & more": "תסמינים, מצב רוח, מים ועוד",
    "Daily wellness logging": "רישום בריאותי יומי",
    "Your data never leaves your phone": "הנתונים שלך לא עוזבים את הטלפון",
    "100% on your device": "100% במכשיר שלך", "Get Started": "התחלה",
    "Cycle tracking, fertile windows & prep": "מעקב מחזור, חלונות פוריים והכנה",
    "I'm planning": "אני מתכננת",
    "Track weeks, baby size, kicks & milestones": "עקבי אחרי שבועות, גודל תינוק, בעיטות ואבני דרך",
    "I'm pregnant": "אני בהריון",
    "We'll tailor Bloomly to your stage.": "נתאים את Bloomly לשלב שלך.",
    "What brings you here?": "מה מביא אותך לכאן?", "Daily reminders": "תזכורות יומיות",
    "First pregnancy?": "הריון ראשון?",
    "This is my first pregnancy": "זה ההריון הראשון שלי",
    "We'll ask for notification permission when you finish setup.": "נבקש הרשאת התראות בסיום ההגדרה.",
    "Starting weight": "משקל התחלתי",
    "Pre-pregnancy weight helps track healthy gain over time.": "משקל לפני ההריון עוזר לעקוב אחרי עלייה בריאה.",
    "A few quick preferences to personalize Bloomly.": "כמה העדפות מהירות להתאמה אישית של Bloomly.",
    "Almost there!": "כמעט סיימנו!", "Weight unit": "יחידת משקל",
    "Key dates": "תאריכים חשובים", "Your journey": "המסע שלך",
    "Preferences": "העדפות", "Welcome": "ברוכה הבאה",
    "A calm, private space to track every moment — from first flutter to final countdown.": "מרחב שקט ופרטי לכל רגע — מהרעד הראשון ועד הספירה לאחור.",
    "Your journey starts here": "המסע שלך מתחיל כאן",
    "Due date has passed — any day now!": "מועד הלידה עבר — בכל יום!",
    "— For %@": "— עבור %@", "Can't wait to meet our little one!": "לא יכולה לחכות לפגוש את הקטן שלנו!",
    "Personal message": "הודעה אישית", "Share Image": "שיתוף תמונה",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — שבוע %lld",
    "Bloomly Week %lld": "Bloomly שבוע %lld",
    "Share Text Update": "שיתוף עדכון טקסט", "Share Update": "שיתוף עדכון",
    "Appointments with reminders": "פגישות עם תזכורות",
    "Trimester-aware nutrition guide": "מדריך תזונה לפי שליש",
    "Statistics & history charts": "סטטיסטיקות וגרפים",
    "Full symptom & weight logging": "רישום מלא של תסמינים ומשקל",
    "Wellness tools: Kegel, kick & contraction timers": "כלי בריאות: Kegel, בעיטות וטיימר צירים",
    "Purchase could not be completed.": "הרכישה לא הושלמה.",
    "Restore Purchases": "שחזור רכישות", "Start Free": "התחלה חינם",
    "Subscriptions will appear when configured in App Store Connect.": "מנויים יופיעו כשיוגדרו ב-App Store Connect.",
    "Unlock the full wellness experience": "פתחי את חוויית הבריאות המלאה",
    "Account": "חשבון", "Appointments": "פגישות", "Baby Names": "שמות תינוק",
    "Bump Journal": "יומן בטן", "Cycle Tracker": "מעקב מחזור",
    "Daily Reminders": "תזכורות יומיות", "Due Date": "מועד לידה",
    "Favorites": "מועדפים", "Features": "תכונות", "Free": "חינם",
    "Log Period": "רישום ווסת", "Mode": "מצב", "New Appointment": "פגישה חדשה",
    "No upcoming appointments": "אין פגישות קרובות",
    "Nutrition Guide": "מדריך תזונה",
    "Used when sharing weekly baby-size updates.": "משמש לשיתוף עדכונים שבועיים על גודל התינוק.",
    "Partner's name (optional)": "שם בן/בת הזוג (אופציונלי)",
    "Partner Sharing": "שיתוף עם בן/בת הזוג", "Past": "עבר", "Planning": "תכנון",
    "Pregnant": "בהריון", "Premium": "פרימיום", "Privacy": "פרטיות",
    "Bloomly stores all your data exclusively on your device.": "Bloomly שומר את כל הנתונים שלך רק במכשיר.",
    "Collect any personal data": "אוספים נתונים אישיים",
    "Send data to servers or the cloud": "שולחים נתונים לשרתים או לענן",
    "Use analytics or tracking SDKs": "משתמשים ב-analytics או SDK מעקב",
    "Show advertisements": "מציגים פרסומות",
    "Require an account or login": "דורשים חשבון או התחברות",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "הנתונים לא עוזבים את האייפון אלא אם גיבית ב-iCloud או iTunes.",
    "Your Privacy Matters": "הפרטיות שלך חשובה", "We do not:": "אנחנו לא:",
    "Settings": "הגדרות", "Statistics": "סטטיסטיקות", "Profile": "פרופיל",
    "Upcoming": "קרובות", "Upgrade to Bloomly Plus": "שדרוג ל-Bloomly Plus",
    "Week": "שבוע", "Weight Tracker": "מעקב משקל",
    "Your name (optional)": "השם שלך (אופציונלי)",
    "Breakfast": "ארוחת בוקר", "Dinner": "ארוחת ערב",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "תזכורות יומיות לשמירה על שתייה וארוחות.",
    "Lunch": "ארוחת צהריים", "Meal Reminders": "תזכורות ארוחות",
    "Meal Schedule": "לוח ארוחות",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "התראות מושבתות. הקישי כאן לפתיחת ההגדרות.",
    "Snack": "חטיף", "Water Reminders": "תזכורות מים", "Water Schedule": "לוח מים",
    "Appearance": "מראה", "Choose a color theme for your app": "בחרי ערכת צבעים לאפליקציה",
    "Language": "שפה",
    "Content like week guides will stay in English until translated.": "תוכן כמו מדריכים שבועיים יישאר באנגלית עד לתרגום.",
    "Your pregnancy companion": "הלוויה שלך בהריון",
    "Best": "הטוב ביותר", "Current": "נוכחי", "Details": "פרטים",
    "Fertile Window": "חלון פוריות", "Gain": "עלייה", "Mood History": "היסטוריית מצב רוח",
    "Next Period": "ווסת הבאה", "No symptom data yet": "עדיין אין נתוני תסמינים",
    "No weight data yet. Log from Home or Weight Tracker.": "עדיין אין נתוני משקל. רשמי מהבית או מעקב משקל.",
    "Ovulation Estimate": "הערכת ביוץ", "Prediction": "תחזית",
    "Symptom Frequency": "תדירות תסמינים", "Water Streak": "רצף שתייה",
    "Weight Over Time": "משקל לאורך זמן", "Tools": "כלים", "Week Guide": "מדריך שבועי",
    "Blush": "סומק", "Coral": "אלמוג", "Dark": "כהה", "Forest": "יער",
    "Lavender": "לבנדר", "Midnight": "חצות", "Mint": "מנטה", "Peach": "אפרסק",
    "Rain": "גשם", "Rose Gold": "זהב ורוד", "Sunset": "שקיעה", "White": "לבן",
    "Duration: %@": "משך: %@", "Interval: %@": "מרווח: %@",
    "Start Contraction": "התחלת ציר", "Stop Contraction": "עצירת ציר",
    "Time contractions": "מדידת צירים", "Contraction Timer": "טיימר צירים",
    "Hydration": "שתייה",
    "Log water from the Home tab quick actions": "רשמי מים מפעולות מהירות בלשונית הבית",
    "Visual water counter": "מונה מים ויזואלי", "Complete!": "הושלם!",
    "Hold": "החזקה", "Hold for 5 seconds, release for 5 seconds": "החזיקי 5 שניות, שחררי 5 שניות",
    "Ready": "מוכנה", "Release": "שחרור", "Rep %lld of 10": "חזרה %lld מתוך 10",
    "Rest": "מנוחה", "Set %lld of 3": "סט %lld מתוך 3", "3 sets × 10 reps": "3 סטים × 10 חזרות",
    "Kegel Timer": "טיימר Kegel", "kicks": "בעיטות",
    "Save Session": "שמירת מפגש", "Tap for Kick": "הקישי לבעיטה",
    "Kick Counter": "מונה בעיטות", "Track baby movements": "מעקב תנועות תינוק",
    "Log weight & view trends": "רישום משקל ומגמות", "Wellness tools": "כלי בריאות",
    "Appointment": "פגישה", "Development": "התפתחות", "Length": "אורך",
    "How You May Feel": "איך את עלולה להרגיש", "Tip": "טיפ",
    "Week %lld Guidance": "הנחיה לשבוע %lld",
    "Your weight entries will appear here.": "רישומי המשקל יופיעו כאן.",
    "Invalid Weight": "משקל לא תקין",
    "Please enter a valid weight in %@.": "הזיני משקל תקין ב-%@.",
    "Latest": "אחרון", "Log Weight": "רישום משקל",
    "Not logged yet": "עדיין לא נרשם",
    "No weight logged yet": "עדיין לא נרשם משקל",
    "Or enter manually": "או הזיני ידנית", "Pre-pregnancy": "לפני ההריון",
    "Previous entry": "רישום קודם", "Set": "הגדרה", "Since Last": "מאז האחרון",
    "%@ since last entry": "%@ מאז הרישום האחרון",
    "Since starting weight": "ממשקל ההתחלה",
    "%@ since starting weight": "%@ ממשקל ההתחלה", "Starting": "התחלתי",
    "Your pre-pregnancy weight helps track healthy gain over time.": "משקל לפני ההריון עוזר לעקוב אחרי עלייה בריאה.",
    "Starting Weight": "משקל התחלתי",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "טיפ: הגדירי משקל התחלתי במעקב משקל.",
    "Tap to add": "הקישי להוספה", "Total Change": "שינוי כולל",
    "Weight Trend": "מגמת משקל",
}
