# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "Arab", "bengali": "Bengali", "chinese": "Tionghoa", "dutch": "Belanda",
    "english": "Inggris", "french": "Prancis", "german": "Jerman", "greek": "Yunani",
    "hebrew": "Ibrani", "hindi": "Hindi", "indonesian": "Indonesia", "italian": "Italia",
    "japanese": "Jepang", "korean": "Korea", "malay": "Melayu", "polish": "Polandia",
    "portuguese": "Portugis", "romanian": "Rumania", "russian": "Rusia",
    "spanish": "Spanyol", "swedish": "Swedia", "thai": "Thailand", "turkish": "Turki",
    "ukrainian": "Ukraina", "vietnamese": "Vietnam",
}
TABLE = {
    "Enter a weight between %@ and %@.": "Masukkan berat antara %1$@ dan %2$@.",
    "Step %lld of %lld": "Langkah %1$lld dari %2$lld",
    "Share with Partner": "Bagikan ke Pasangan",
    "Camera": "Kamera",
    "Add your first photo to start your visual journal.": "Tambahkan foto pertama untuk memulai jurnal visual Anda.",
    "No bump photos yet": "Belum ada foto perut",
    "Optional note": "Catatan opsional",
    "Photo Library": "Galeri Foto",
    "Save Photo": "Simpan Foto",
    "Capture your growing bump each week and watch your journey unfold.": "Abadikan perut yang tumbuh setiap minggu dan saksikan perjalanan Anda.",
    "Week %lld Bump": "Perut Minggu %lld",
    "Back": "Kembali", "Cancel": "Batal", "Continue": "Lanjut", "Date": "Tanggal",
    "Done!": "Selesai!", "Gender": "Jenis Kelamin", "History": "Riwayat", "Letter": "Huruf",
    "Log": "Catat", "Logged": "Tercatat", "ongoing": "berlangsung",
    "(optional)": "(opsional)", "Pause": "Jeda",
    "%@ is part of Bloomly Plus": "%@ bagian dari Bloomly Plus",
    "Reset": "Atur Ulang", "Save": "Simpan", "Severity": "Tingkat",
    "Start": "Mulai", "Style": "Gaya", "Upgrade": "Upgrade", "Week %lld": "Minggu %lld",
    "Period ended": "Menstruasi selesai", "Day Summary": "Ringkasan Hari", "Notes": "Catatan",
    "Daily Log": "Catatan Harian", "Daily goal: 8 glasses": "Target harian: 8 gelas",
    "Daily Tip": "Tip Harian", "%lld days until due date": "%lld hari menuju tanggal lahir",
    "Your due date has passed": "Tanggal lahir Anda telah lewat", "glasses of water": "gelas air",
    "How are you feeling?": "Bagaimana perasaan Anda?", "Mood": "Suasana Hati", "Planning Mode": "Mode Perencanaan",
    "Track your cycle and prepare for your journey.": "Lacak siklus Anda dan persiapkan perjalanan.",
    "Pregnancy Progress": "Progres Kehamilan", "Quick Log": "Catat Cepat",
    "Symptoms": "Gejala", "Home": "Beranda", "Water": "Air", "Water Intake": "Asupan Air",
    "Week %lld of 40": "Minggu %lld dari 40", "Weight": "Berat",
    "Due date": "Tanggal lahir", "Last period": "Menstruasi terakhir",
    "Last period start": "Awal menstruasi terakhir", "Last menstrual period": "Menstruasi terakhir",
    "When did your last period start? You can log more dates anytime.": "Kapan menstruasi terakhir dimulai? Anda bisa mencatat tanggal kapan saja.",
    "Cycle insights appear on your Home tab": "Wawasan siklus muncul di tab Beranda",
    "Track your cycle": "Lacak siklus Anda",
    "We'll calculate your week and due date.": "Kami akan menghitung minggu dan tanggal lahir.",
    "When did your journey begin?": "Kapan perjalanan Anda dimulai?",
    "Baby size, tips & milestones": "Ukuran bayi, tips & tonggak",
    "Week-by-week guides": "Panduan minggu demi minggu",
    "Symptoms, mood, water & more": "Gejala, suasana hati, air & lainnya",
    "Daily wellness logging": "Pencatatan kesehatan harian",
    "Your data never leaves your phone": "Data Anda tidak pernah meninggalkan ponsel",
    "100% on your device": "100% di perangkat Anda", "Get Started": "Mulai",
    "Cycle tracking, fertile windows & prep": "Pelacakan siklus, masa subur & persiapan",
    "I'm planning": "Saya merencanakan",
    "Track weeks, baby size, kicks & milestones": "Lacak minggu, ukuran bayi, tendangan & tonggak",
    "I'm pregnant": "Saya hamil",
    "We'll tailor Bloomly to your stage.": "Kami akan menyesuaikan Bloomly dengan tahap Anda.",
    "What brings you here?": "Apa yang membawa Anda ke sini?", "Daily reminders": "Pengingat harian",
    "First pregnancy?": "Kehamilan pertama?",
    "This is my first pregnancy": "Ini kehamilan pertama saya",
    "We'll ask for notification permission when you finish setup.": "Kami akan meminta izin notifikasi saat setup selesai.",
    "Starting weight": "Berat awal",
    "Pre-pregnancy weight helps track healthy gain over time.": "Berat sebelum hamil membantu melacak kenaikan sehat.",
    "A few quick preferences to personalize Bloomly.": "Beberapa preferensi cepat untuk personalisasi Bloomly.",
    "Almost there!": "Hampir selesai!", "Weight unit": "Satuan berat",
    "Key dates": "Tanggal penting", "Your journey": "Perjalanan Anda",
    "Preferences": "Preferensi", "Welcome": "Selamat datang",
    "A calm, private space to track every moment — from first flutter to final countdown.": "Ruang tenang dan pribadi untuk setiap momen — dari gerakan pertama hingga hitung mundur.",
    "Your journey starts here": "Perjalanan Anda dimulai di sini",
    "Due date has passed — any day now!": "Tanggal lahir telah lewat — kapan saja!",
    "— For %@": "— Untuk %@", "Can't wait to meet our little one!": "Tak sabar bertemu buah hati kami!",
    "Personal message": "Pesan pribadi", "Share Image": "Bagikan Gambar",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — Minggu %lld",
    "Bloomly Week %lld": "Bloomly Minggu %lld",
    "Share Text Update": "Bagikan Pembaruan Teks", "Share Update": "Bagikan Pembaruan",
    "Appointments with reminders": "Janji temu dengan pengingat",
    "Trimester-aware nutrition guide": "Panduan nutrisi per trimester",
    "Statistics & history charts": "Statistik & grafik riwayat",
    "Full symptom & weight logging": "Pencatatan gejala & berat lengkap",
    "Wellness tools: Kegel, kick & contraction timers": "Alat kesehatan: Kegel, tendangan & timer kontraksi",
    "Purchase could not be completed.": "Pembelian tidak dapat diselesaikan.",
    "Restore Purchases": "Pulihkan Pembelian", "Start Free": "Mulai Gratis",
    "Subscriptions will appear when configured in App Store Connect.": "Langganan akan muncul saat dikonfigurasi di App Store Connect.",
    "Unlock the full wellness experience": "Buka pengalaman kesehatan penuh",
    "Account": "Akun", "Appointments": "Janji Temu", "Baby Names": "Nama Bayi",
    "Bump Journal": "Jurnal Perut", "Cycle Tracker": "Pelacak Siklus",
    "Daily Reminders": "Pengingat Harian", "Due Date": "Tanggal Lahir",
    "Favorites": "Favorit", "Features": "Fitur", "Free": "Gratis",
    "Log Period": "Catat Menstruasi", "Mode": "Mode", "New Appointment": "Janji Baru",
    "No upcoming appointments": "Tidak ada janji mendatang",
    "Nutrition Guide": "Panduan Nutrisi",
    "Used when sharing weekly baby-size updates.": "Digunakan saat membagikan pembaruan ukuran bayi mingguan.",
    "Partner's name (optional)": "Nama pasangan (opsional)",
    "Partner Sharing": "Berbagi dengan Pasangan", "Past": "Lalu", "Planning": "Perencanaan",
    "Pregnant": "Hamil", "Premium": "Premium", "Privacy": "Privasi",
    "Bloomly stores all your data exclusively on your device.": "Bloomly menyimpan semua data hanya di perangkat Anda.",
    "Collect any personal data": "Mengumpulkan data pribadi",
    "Send data to servers or the cloud": "Mengirim data ke server atau cloud",
    "Use analytics or tracking SDKs": "Menggunakan analytics atau SDK pelacakan",
    "Show advertisements": "Menampilkan iklan",
    "Require an account or login": "Memerlukan akun atau login",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "Data tidak meninggalkan iPhone kecuali backup via iCloud atau iTunes.",
    "Your Privacy Matters": "Privasi Anda Penting", "We do not:": "Kami tidak:",
    "Settings": "Pengaturan", "Statistics": "Statistik", "Profile": "Profil",
    "Upcoming": "Mendatang", "Upgrade to Bloomly Plus": "Upgrade ke Bloomly Plus",
    "Week": "Minggu", "Weight Tracker": "Pelacak Berat",
    "Your name (optional)": "Nama Anda (opsional)",
    "Breakfast": "Sarapan", "Dinner": "Makan Malam",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "Pengingat harian untuk tetap terhidrasi dan makan teratur.",
    "Lunch": "Makan Siang", "Meal Reminders": "Pengingat Makan",
    "Meal Schedule": "Jadwal Makan",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "Notifikasi dinonaktifkan. Ketuk di sini untuk buka Pengaturan.",
    "Snack": "Camilan", "Water Reminders": "Pengingat Air", "Water Schedule": "Jadwal Air",
    "Appearance": "Tampilan", "Choose a color theme for your app": "Pilih tema warna untuk aplikasi",
    "Language": "Bahasa",
    "Content like week guides will stay in English until translated.": "Konten seperti panduan minggu akan tetap dalam Bahasa Inggris hingga diterjemahkan.",
    "Your pregnancy companion": "Pendamping kehamilan Anda",
    "Best": "Terbaik", "Current": "Saat Ini", "Details": "Detail",
    "Fertile Window": "Masa Subur", "Gain": "Kenaikan", "Mood History": "Riwayat Suasana Hati",
    "Next Period": "Menstruasi Berikutnya", "No symptom data yet": "Belum ada data gejala",
    "No weight data yet. Log from Home or Weight Tracker.": "Belum ada data berat. Catat dari Beranda atau Pelacak Berat.",
    "Ovulation Estimate": "Perkiraan Ovulasi", "Prediction": "Prediksi",
    "Symptom Frequency": "Frekuensi Gejala", "Water Streak": "Streak Minum Air",
    "Weight Over Time": "Berat Seiring Waktu", "Tools": "Alat", "Week Guide": "Panduan Minggu",
    "Blush": "Blush", "Coral": "Koral", "Dark": "Gelap", "Forest": "Hutan",
    "Lavender": "Lavender", "Midnight": "Tengah Malam", "Mint": "Mint", "Peach": "Persik",
    "Rain": "Hujan", "Rose Gold": "Rose Gold", "Sunset": "Senja", "White": "Putih",
    "Duration: %@": "Durasi: %@", "Interval: %@": "Interval: %@",
    "Start Contraction": "Mulai Kontraksi", "Stop Contraction": "Hentikan Kontraksi",
    "Time contractions": "Ukur kontraksi", "Contraction Timer": "Timer Kontraksi",
    "Hydration": "Hidrasi",
    "Log water from the Home tab quick actions": "Catat air dari aksi cepat di tab Beranda",
    "Visual water counter": "Penghitung air visual", "Complete!": "Selesai!",
    "Hold": "Tahan", "Hold for 5 seconds, release for 5 seconds": "Tahan 5 detik, lepas 5 detik",
    "Ready": "Siap", "Release": "Lepas", "Rep %lld of 10": "Rep %lld dari 10",
    "Rest": "Istirahat", "Set %lld of 3": "Set %lld dari 3", "3 sets × 10 reps": "3 set × 10 rep",
    "Kegel Timer": "Timer Kegel", "kicks": "tendangan",
    "Save Session": "Simpan Sesi", "Tap for Kick": "Ketuk untuk Tendangan",
    "Kick Counter": "Penghitung Tendangan", "Track baby movements": "Lacak gerakan bayi",
    "Log weight & view trends": "Catat berat & lihat tren", "Wellness tools": "Alat kesehatan",
    "Appointment": "Janji", "Development": "Perkembangan", "Length": "Panjang",
    "How You May Feel": "Bagaimana Perasaan Anda", "Tip": "Tip",
    "Week %lld Guidance": "Panduan Minggu %lld",
    "Your weight entries will appear here.": "Entri berat akan muncul di sini.",
    "Invalid Weight": "Berat Tidak Valid",
    "Please enter a valid weight in %@.": "Masukkan berat valid dalam %@.",
    "Latest": "Terbaru", "Log Weight": "Catat Berat",
    "Not logged yet": "Belum dicatat",
    "No weight logged yet": "Belum ada berat tercatat",
    "Or enter manually": "Atau masukkan manual", "Pre-pregnancy": "Sebelum hamil",
    "Previous entry": "Entri sebelumnya", "Set": "Atur", "Since Last": "Sejak Terakhir",
    "%@ since last entry": "%@ sejak entri terakhir",
    "Since starting weight": "Sejak berat awal",
    "%@ since starting weight": "%@ sejak berat awal", "Starting": "Awal",
    "Your pre-pregnancy weight helps track healthy gain over time.": "Berat sebelum hamil membantu melacak kenaikan sehat.",
    "Starting Weight": "Berat Awal",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "Tip: atur berat awal di Pelacak Berat.",
    "Tap to add": "Ketuk untuk tambah", "Total Change": "Perubahan Total",
    "Weight Trend": "Tren Berat",
}
