# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "Arab", "bengali": "Bengali", "chinese": "Cina", "dutch": "Belanda",
    "english": "Inggeris", "french": "Perancis", "german": "Jerman", "greek": "Yunani",
    "hebrew": "Ibrani", "hindi": "Hindi", "indonesian": "Indonesia", "italian": "Itali",
    "japanese": "Jepun", "korean": "Korea", "malay": "Melayu", "polish": "Poland",
    "portuguese": "Portugis", "romanian": "Romania", "russian": "Rusia",
    "spanish": "Sepanyol", "swedish": "Sweden", "thai": "Thai", "turkish": "Turki",
    "ukrainian": "Ukraine", "vietnamese": "Vietnam",
}
TABLE = {
    "Enter a weight between %@ and %@.": "Masukkan berat antara %1$@ dan %2$@.",
    "Step %lld of %lld": "Langkah %1$lld daripada %2$lld",
    "Share with Partner": "Kongsi dengan Pasangan",
    "Camera": "Kamera",
    "Add your first photo to start your visual journal.": "Tambah foto pertama untuk memulakan jurnal visual anda.",
    "No bump photos yet": "Tiada foto perut lagi",
    "Optional note": "Nota pilihan",
    "Photo Library": "Galeri Foto",
    "Save Photo": "Simpan Foto",
    "Capture your growing bump each week and watch your journey unfold.": "Rakam perut yang membesar setiap minggu dan saksikan perjalanan anda.",
    "Week %lld Bump": "Perut Minggu %lld",
    "Back": "Kembali", "Cancel": "Batal", "Continue": "Teruskan", "Date": "Tarikh",
    "Done!": "Selesai!", "Gender": "Jantina", "History": "Sejarah", "Letter": "Huruf",
    "Log": "Log", "Logged": "Dilog", "ongoing": "berterusan",
    "(optional)": "(pilihan)", "Pause": "Jeda",
    "%@ is part of Bloomly Plus": "%@ adalah sebahagian daripada Bloomly Plus",
    "Reset": "Set Semula", "Save": "Simpan", "Severity": "Keterukan",
    "Start": "Mula", "Style": "Gaya", "Upgrade": "Naik Taraf", "Week %lld": "Minggu %lld",
    "Period ended": "Haid tamat", "Day Summary": "Ringkasan Hari", "Notes": "Nota",
    "Daily Log": "Log Harian", "Daily goal: 8 glasses": "Matlamat harian: 8 gelas",
    "Daily Tip": "Tip Harian", "%lld days until due date": "%lld hari sehingga tarikh jangkaan",
    "Your due date has passed": "Tarikh jangkaan anda telah berlalu", "glasses of water": "gelas air",
    "How are you feeling?": "Bagaimana perasaan anda?", "Mood": "Mood", "Planning Mode": "Mod Perancangan",
    "Track your cycle and prepare for your journey.": "Jejaki kitaran anda dan bersedia untuk perjalanan.",
    "Pregnancy Progress": "Kemajuan Kehamilan", "Quick Log": "Log Pantas",
    "Symptoms": "Simptom", "Home": "Utama", "Water": "Air", "Water Intake": "Pengambilan Air",
    "Week %lld of 40": "Minggu %lld daripada 40", "Weight": "Berat",
    "Due date": "Tarikh jangkaan", "Last period": "Haid terakhir",
    "Last period start": "Permulaan haid terakhir", "Last menstrual period": "Haid terakhir",
    "When did your last period start? You can log more dates anytime.": "Bila haid terakhir bermula? Anda boleh log tarikh pada bila-bila masa.",
    "Cycle insights appear on your Home tab": "Wawasan kitaran muncul di tab Utama",
    "Track your cycle": "Jejaki kitaran anda",
    "We'll calculate your week and due date.": "Kami akan kira minggu dan tarikh jangkaan.",
    "When did your journey begin?": "Bila perjalanan anda bermula?",
    "Baby size, tips & milestones": "Saiz bayi, tip & pencapaian",
    "Week-by-week guides": "Panduan minggu demi minggu",
    "Symptoms, mood, water & more": "Simptom, mood, air & lagi",
    "Daily wellness logging": "Log kesejahteraan harian",
    "Your data never leaves your phone": "Data anda tidak pernah meninggalkan telefon",
    "100% on your device": "100% pada peranti anda", "Get Started": "Mula",
    "Cycle tracking, fertile windows & prep": "Jejakan kitaran, tempoh subur & persediaan",
    "I'm planning": "Saya merancang",
    "Track weeks, baby size, kicks & milestones": "Jejaki minggu, saiz bayi, tendangan & pencapaian",
    "I'm pregnant": "Saya hamil",
    "We'll tailor Bloomly to your stage.": "Kami akan sesuaikan Bloomly dengan peringkat anda.",
    "What brings you here?": "Apa yang membawa anda ke sini?", "Daily reminders": "Peringatan harian",
    "First pregnancy?": "Kehamilan pertama?",
    "This is my first pregnancy": "Ini kehamilan pertama saya",
    "We'll ask for notification permission when you finish setup.": "Kami akan minta kebenaran notifikasi apabila setup selesai.",
    "Starting weight": "Berat permulaan",
    "Pre-pregnancy weight helps track healthy gain over time.": "Berat sebelum hamil membantu jejak kenaikan sihat.",
    "A few quick preferences to personalize Bloomly.": "Beberapa pilihan pantas untuk personalisasi Bloomly.",
    "Almost there!": "Hampir selesai!", "Weight unit": "Unit berat",
    "Key dates": "Tarikh penting", "Your journey": "Perjalanan anda",
    "Preferences": "Pilihan", "Welcome": "Selamat datang",
    "A calm, private space to track every moment — from first flutter to final countdown.": "Ruang tenang dan peribadi untuk setiap detik — dari gerakan pertama hingga kira detik.",
    "Your journey starts here": "Perjalanan anda bermula di sini",
    "Due date has passed — any day now!": "Tarikh jangkaan berlalu — bila-bila masa!",
    "— For %@": "— Untuk %@", "Can't wait to meet our little one!": "Tak sabar jumpa si manja kami!",
    "Personal message": "Mesej peribadi", "Share Image": "Kongsi Imej",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — Minggu %lld",
    "Bloomly Week %lld": "Bloomly Minggu %lld",
    "Share Text Update": "Kongsi Kemas Kini Teks", "Share Update": "Kongsi Kemas Kini",
    "Appointments with reminders": "Temujanji dengan peringatan",
    "Trimester-aware nutrition guide": "Panduan pemakanan mengikut trimester",
    "Statistics & history charts": "Statistik & carta sejarah",
    "Full symptom & weight logging": "Log simptom & berat penuh",
    "Wellness tools: Kegel, kick & contraction timers": "Alat kesejahteraan: Kegel, tendangan & pemasa kontraksi",
    "Purchase could not be completed.": "Pembelian tidak dapat diselesaikan.",
    "Restore Purchases": "Pulihkan Pembelian", "Start Free": "Mula Percuma",
    "Subscriptions will appear when configured in App Store Connect.": "Langganan akan muncul apabila dikonfigurasi di App Store Connect.",
    "Unlock the full wellness experience": "Buka pengalaman kesejahteraan penuh",
    "Account": "Akaun", "Appointments": "Temujanji", "Baby Names": "Nama Bayi",
    "Bump Journal": "Jurnal Perut", "Cycle Tracker": "Penjejak Kitaran",
    "Daily Reminders": "Peringatan Harian", "Due Date": "Tarikh Jangkaan",
    "Favorites": "Kegemaran", "Features": "Ciri", "Free": "Percuma",
    "Log Period": "Log Haid", "Mode": "Mod", "New Appointment": "Temujanji Baru",
    "No upcoming appointments": "Tiada temujanji akan datang",
    "Nutrition Guide": "Panduan Pemakanan",
    "Used when sharing weekly baby-size updates.": "Digunakan semasa kongsi kemas kini saiz bayi mingguan.",
    "Partner's name (optional)": "Nama pasangan (pilihan)",
    "Partner Sharing": "Perkongsian Pasangan", "Past": "Lalu", "Planning": "Perancangan",
    "Pregnant": "Hamil", "Premium": "Premium", "Privacy": "Privasi",
    "Bloomly stores all your data exclusively on your device.": "Bloomly menyimpan semua data hanya pada peranti anda.",
    "Collect any personal data": "Mengumpul data peribadi",
    "Send data to servers or the cloud": "Menghantar data ke pelayan atau awan",
    "Use analytics or tracking SDKs": "Menggunakan analitik atau SDK penjejakan",
    "Show advertisements": "Memaparkan iklan",
    "Require an account or login": "Memerlukan akaun atau log masuk",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "Data tidak meninggalkan iPhone melainkan sandaran melalui iCloud atau iTunes.",
    "Your Privacy Matters": "Privasi Anda Penting", "We do not:": "Kami tidak:",
    "Settings": "Tetapan", "Statistics": "Statistik", "Profile": "Profil",
    "Upcoming": "Akan Datang", "Upgrade to Bloomly Plus": "Naik Taraf ke Bloomly Plus",
    "Week": "Minggu", "Weight Tracker": "Penjejak Berat",
    "Your name (optional)": "Nama anda (pilihan)",
    "Breakfast": "Sarapan", "Dinner": "Makan Malam",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "Peringatan harian untuk kekal terhidrat dan makan mengikut jadual.",
    "Lunch": "Makan Tengahari", "Meal Reminders": "Peringatan Makan",
    "Meal Schedule": "Jadual Makan",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "Notifikasi dimatikan. Ketik di sini untuk buka Tetapan.",
    "Snack": "Snek", "Water Reminders": "Peringatan Air", "Water Schedule": "Jadual Air",
    "Appearance": "Penampilan", "Choose a color theme for your app": "Pilih tema warna untuk aplikasi",
    "Language": "Bahasa",
    "Content like week guides will stay in English until translated.": "Kandungan seperti panduan minggu kekal dalam Inggeris sehingga diterjemah.",
    "Your pregnancy companion": "Teman kehamilan anda",
    "Best": "Terbaik", "Current": "Semasa", "Details": "Butiran",
    "Fertile Window": "Tempoh Subur", "Gain": "Kenaikan", "Mood History": "Sejarah Mood",
    "Next Period": "Haid Seterusnya", "No symptom data yet": "Tiada data simptom lagi",
    "No weight data yet. Log from Home or Weight Tracker.": "Tiada data berat lagi. Log dari Utama atau Penjejak Berat.",
    "Ovulation Estimate": "Anggaran Ovulasi", "Prediction": "Ramalan",
    "Symptom Frequency": "Kekerapan Simptom", "Water Streak": "Rentetan Minum Air",
    "Weight Over Time": "Berat Sepanjang Masa", "Tools": "Alat", "Week Guide": "Panduan Minggu",
    "Blush": "Blush", "Coral": "Koral", "Dark": "Gelap", "Forest": "Hutan",
    "Lavender": "Lavender", "Midnight": "Tengah Malam", "Mint": "Mint", "Peach": "Pic",
    "Rain": "Hujan", "Rose Gold": "Rose Gold", "Sunset": "Senja", "White": "Putih",
    "Duration: %@": "Tempoh: %@", "Interval: %@": "Selang: %@",
    "Start Contraction": "Mula Kontraksi", "Stop Contraction": "Henti Kontraksi",
    "Time contractions": "Ukur kontraksi", "Contraction Timer": "Pemasa Kontraksi",
    "Hydration": "Hidrasi",
    "Log water from the Home tab quick actions": "Log air dari tindakan pantas tab Utama",
    "Visual water counter": "Kaunter air visual", "Complete!": "Selesai!",
    "Hold": "Tahan", "Hold for 5 seconds, release for 5 seconds": "Tahan 5 saat, lepas 5 saat",
    "Ready": "Sedia", "Release": "Lepas", "Rep %lld of 10": "Rep %lld daripada 10",
    "Rest": "Rehat", "Set %lld of 3": "Set %lld daripada 3", "3 sets × 10 reps": "3 set × 10 rep",
    "Kegel Timer": "Pemasa Kegel", "kicks": "tendangan",
    "Save Session": "Simpan Sesi", "Tap for Kick": "Ketik untuk Tendangan",
    "Kick Counter": "Kaunter Tendangan", "Track baby movements": "Jejaki pergerakan bayi",
    "Log weight & view trends": "Log berat & lihat trend", "Wellness tools": "Alat kesejahteraan",
    "Appointment": "Temujanji", "Development": "Perkembangan", "Length": "Panjang",
    "How You May Feel": "Bagaimana Perasaan Anda", "Tip": "Tip",
    "Week %lld Guidance": "Panduan Minggu %lld",
    "Your weight entries will appear here.": "Entri berat akan muncul di sini.",
    "Invalid Weight": "Berat Tidak Sah",
    "Please enter a valid weight in %@.": "Masukkan berat sah dalam %@.",
    "Latest": "Terkini", "Log Weight": "Log Berat",
    "Not logged yet": "Belum dilog",
    "No weight logged yet": "Tiada berat dilog lagi",
    "Or enter manually": "Atau masukkan manual", "Pre-pregnancy": "Sebelum hamil",
    "Previous entry": "Entri sebelumnya", "Set": "Tetapkan", "Since Last": "Sejak Terakhir",
    "%@ since last entry": "%@ sejak entri terakhir",
    "Since starting weight": "Sejak berat permulaan",
    "%@ since starting weight": "%@ sejak berat permulaan", "Starting": "Permulaan",
    "Your pre-pregnancy weight helps track healthy gain over time.": "Berat sebelum hamil membantu jejak kenaikan sihat.",
    "Starting Weight": "Berat Permulaan",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "Tip: tetapkan berat permulaan dalam Penjejak Berat.",
    "Tap to add": "Ketik untuk tambah", "Total Change": "Perubahan Jumlah",
    "Weight Trend": "Trend Berat",
}
