# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "Arabă", "bengali": "Bengaleză", "chinese": "Chineză", "dutch": "Olandeză",
    "english": "Engleză", "french": "Franceză", "german": "Germană", "greek": "Greacă",
    "hebrew": "Ebraică", "hindi": "Hindi", "indonesian": "Indoneziană", "italian": "Italiană",
    "japanese": "Japoneză", "korean": "Coreeană", "malay": "Malaeză", "polish": "Poloneză",
    "portuguese": "Portugheză", "romanian": "Română", "russian": "Rusă",
    "spanish": "Spaniolă", "swedish": "Suedeză", "thai": "Thailandeză", "turkish": "Turcă",
    "ukrainian": "Ucraineană", "vietnamese": "Vietnameză",
}
TABLE = {
    "Enter a weight between %@ and %@.": "Introduceți o greutate între %1$@ și %2$@.",
    "Step %lld of %lld": "Pasul %1$lld din %2$lld",
    "Share with Partner": "Distribuie partenerului",
    "Camera": "Cameră",
    "Add your first photo to start your visual journal.": "Adaugă prima fotografie pentru a începe jurnalul vizual.",
    "No bump photos yet": "Nicio fotografie a burticii încă",
    "Optional note": "Notă opțională",
    "Photo Library": "Galerie foto",
    "Save Photo": "Salvează fotografia",
    "Capture your growing bump each week and watch your journey unfold.": "Surprinde burtica în creștere în fiecare săptămână și urmărește călătoria.",
    "Week %lld Bump": "Burtică săptămâna %lld",
    "Back": "Înapoi", "Cancel": "Anulează", "Continue": "Continuă", "Date": "Dată",
    "Done!": "Gata!", "Gender": "Gen", "History": "Istoric", "Letter": "Literă",
    "Log": "Înregistrează", "Logged": "Înregistrat", "ongoing": "în curs",
    "(optional)": "(opțional)", "Pause": "Pauză",
    "%@ is part of Bloomly Plus": "%@ face parte din Bloomly Plus",
    "Reset": "Resetează", "Save": "Salvează", "Severity": "Severitate",
    "Start": "Start", "Style": "Stil", "Upgrade": "Upgrade", "Week %lld": "Săptămâna %lld",
    "Period ended": "Menstruația s-a terminat", "Day Summary": "Rezumat zilnic", "Notes": "Notițe",
    "Daily Log": "Jurnal zilnic", "Daily goal: 8 glasses": "Obiectiv zilnic: 8 pahare",
    "Daily Tip": "Sfat zilnic", "%lld days until due date": "%lld zile până la termen",
    "Your due date has passed": "Termenul estimat a trecut", "glasses of water": "pahare de apă",
    "How are you feeling?": "Cum te simți?", "Mood": "Stare", "Planning Mode": "Mod planificare",
    "Track your cycle and prepare for your journey.": "Urmărește ciclul și pregătește-te pentru călătorie.",
    "Pregnancy Progress": "Progresul sarcinii", "Quick Log": "Înregistrare rapidă",
    "Symptoms": "Simptome", "Home": "Acasă", "Water": "Apă", "Water Intake": "Consum de apă",
    "Week %lld of 40": "Săptămâna %lld din 40", "Weight": "Greutate",
    "Due date": "Termen estimat", "Last period": "Ultima menstruație",
    "Last period start": "Începutul ultimei menstruații", "Last menstrual period": "Ultima menstruație",
    "When did your last period start? You can log more dates anytime.": "Când a început ultima menstruație? Poți înregistra date oricând.",
    "Cycle insights appear on your Home tab": "Informațiile despre ciclu apar în fila Acasă",
    "Track your cycle": "Urmărește ciclul",
    "We'll calculate your week and due date.": "Vom calcula săptămâna și termenul estimat.",
    "When did your journey begin?": "Când a început călătoria ta?",
    "Baby size, tips & milestones": "Dimensiune bebeluș, sfaturi și repere",
    "Week-by-week guides": "Ghiduri săptămână de săptămână",
    "Symptoms, mood, water & more": "Simptome, stare, apă și altele",
    "Daily wellness logging": "Înregistrare zilnică wellness",
    "Your data never leaves your phone": "Datele tale nu părăsesc telefonul",
    "100% on your device": "100% pe dispozitivul tău", "Get Started": "Începe",
    "Cycle tracking, fertile windows & prep": "Urmărire ciclu, fereastră fertilă și pregătire",
    "I'm planning": "Planific",
    "Track weeks, baby size, kicks & milestones": "Urmărește săptămâni, dimensiune, lovituri și repere",
    "I'm pregnant": "Sunt însărcinată",
    "We'll tailor Bloomly to your stage.": "Vom adapta Bloomly etapei tale.",
    "What brings you here?": "Ce te aduce aici?", "Daily reminders": "Memento-uri zilnice",
    "First pregnancy?": "Prima sarcină?",
    "This is my first pregnancy": "Aceasta este prima mea sarcină",
    "We'll ask for notification permission when you finish setup.": "Vom cere permisiunea pentru notificări la finalizarea configurării.",
    "Starting weight": "Greutate inițială",
    "Pre-pregnancy weight helps track healthy gain over time.": "Greutatea pre-sarcină ajută la urmărirea creșterii sănătoase.",
    "A few quick preferences to personalize Bloomly.": "Câteva preferințe rapide pentru personalizarea Bloomly.",
    "Almost there!": "Aproape gata!", "Weight unit": "Unitate greutate",
    "Key dates": "Date cheie", "Your journey": "Călătoria ta",
    "Preferences": "Preferințe", "Welcome": "Bun venit",
    "A calm, private space to track every moment — from first flutter to final countdown.": "Un spațiu calm și privat pentru fiecare moment — de la primul flutter la numărătoarea inversă.",
    "Your journey starts here": "Călătoria ta începe aici",
    "Due date has passed — any day now!": "Termenul a trecut — oricând acum!",
    "— For %@": "— Pentru %@", "Can't wait to meet our little one!": "Abia aștept să ne întâlnim cu micuțul!",
    "Personal message": "Mesaj personal", "Share Image": "Distribuie imagine",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — Săptămâna %lld",
    "Bloomly Week %lld": "Bloomly Săptămâna %lld",
    "Share Text Update": "Distribuie actualizare text", "Share Update": "Distribuie actualizare",
    "Appointments with reminders": "Programări cu memento-uri",
    "Trimester-aware nutrition guide": "Ghid nutriție pe trimestre",
    "Statistics & history charts": "Statistici și grafice istoric",
    "Full symptom & weight logging": "Înregistrare completă simptome și greutate",
    "Wellness tools: Kegel, kick & contraction timers": "Instrumente wellness: Kegel, lovituri și cronometru contracții",
    "Purchase could not be completed.": "Achiziția nu a putut fi finalizată.",
    "Restore Purchases": "Restaurează achizițiile", "Start Free": "Începe gratuit",
    "Subscriptions will appear when configured in App Store Connect.": "Abonamentele vor apărea când sunt configurate în App Store Connect.",
    "Unlock the full wellness experience": "Deblochează experiența wellness completă",
    "Account": "Cont", "Appointments": "Programări", "Baby Names": "Nume bebeluș",
    "Bump Journal": "Jurnal burtică", "Cycle Tracker": "Urmărire ciclu",
    "Daily Reminders": "Memento-uri zilnice", "Due Date": "Termen estimat",
    "Favorites": "Favorite", "Features": "Funcții", "Free": "Gratuit",
    "Log Period": "Înregistrează menstruația", "Mode": "Mod", "New Appointment": "Programare nouă",
    "No upcoming appointments": "Nicio programare viitoare",
    "Nutrition Guide": "Ghid nutriție",
    "Used when sharing weekly baby-size updates.": "Folosit la distribuirea actualizărilor săptămânale despre bebeluș.",
    "Partner's name (optional)": "Numele partenerului (opțional)",
    "Partner Sharing": "Partajare cu partenerul", "Past": "Trecut", "Planning": "Planificare",
    "Pregnant": "Însărcinată", "Premium": "Premium", "Privacy": "Confidențialitate",
    "Bloomly stores all your data exclusively on your device.": "Bloomly stochează toate datele exclusiv pe dispozitivul tău.",
    "Collect any personal data": "Colectăm date personale",
    "Send data to servers or the cloud": "Trimitem date pe servere sau cloud",
    "Use analytics or tracking SDKs": "Folosim analytics sau SDK-uri de urmărire",
    "Show advertisements": "Afișăm reclame",
    "Require an account or login": "Cerem cont sau autentificare",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "Datele nu părăsesc iPhone-ul decât dacă faci backup prin iCloud sau iTunes.",
    "Your Privacy Matters": "Confidențialitatea ta contează", "We do not:": "Nu:",
    "Settings": "Setări", "Statistics": "Statistici", "Profile": "Profil",
    "Upcoming": "Viitoare", "Upgrade to Bloomly Plus": "Upgrade la Bloomly Plus",
    "Week": "Săptămână", "Weight Tracker": "Urmărire greutate",
    "Your name (optional)": "Numele tău (opțional)",
    "Breakfast": "Mic dejun", "Dinner": "Cină",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "Memento-uri zilnice pentru hidratare și mese la timp.",
    "Lunch": "Prânz", "Meal Reminders": "Memento-uri mese",
    "Meal Schedule": "Program mese",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "Notificările sunt dezactivate. Atinge aici pentru Setări.",
    "Snack": "Gustare", "Water Reminders": "Memento-uri apă", "Water Schedule": "Program apă",
    "Appearance": "Aspect", "Choose a color theme for your app": "Alege o temă de culoare pentru aplicație",
    "Language": "Limbă",
    "Content like week guides will stay in English until translated.": "Conținutul precum ghidurile săptămânale rămâne în engleză până la traducere.",
    "Your pregnancy companion": "Companionul tău de sarcină",
    "Best": "Cel mai bun", "Current": "Curent", "Details": "Detalii",
    "Fertile Window": "Fereastră fertilă", "Gain": "Creștere", "Mood History": "Istoric stare",
    "Next Period": "Următoarea menstruație", "No symptom data yet": "Nicio dată despre simptome încă",
    "No weight data yet. Log from Home or Weight Tracker.": "Nicio dată despre greutate. Înregistrează din Acasă sau Urmărire greutate.",
    "Ovulation Estimate": "Estimare ovulație", "Prediction": "Predicție",
    "Symptom Frequency": "Frecvență simptome", "Water Streak": "Serie apă",
    "Weight Over Time": "Greutate în timp", "Tools": "Instrumente", "Week Guide": "Ghid săptămânal",
    "Blush": "Blush", "Coral": "Coral", "Dark": "Întunecat", "Forest": "Pădure",
    "Lavender": "Lavandă", "Midnight": "Miezul nopții", "Mint": "Mentă", "Peach": "Piersică",
    "Rain": "Ploaie", "Rose Gold": "Aur roz", "Sunset": "Apus", "White": "Alb",
    "Duration: %@": "Durată: %@", "Interval: %@": "Interval: %@",
    "Start Contraction": "Începe contracția", "Stop Contraction": "Oprește contracția",
    "Time contractions": "Cronometrează contracțiile", "Contraction Timer": "Cronometru contracții",
    "Hydration": "Hidratare",
    "Log water from the Home tab quick actions": "Înregistrează apa din acțiunile rapide Acasă",
    "Visual water counter": "Contor vizual apă", "Complete!": "Complet!",
    "Hold": "Ține", "Hold for 5 seconds, release for 5 seconds": "Ține 5 secunde, eliberează 5 secunde",
    "Ready": "Pregătit", "Release": "Eliberează", "Rep %lld of 10": "Rep %lld din 10",
    "Rest": "Pauză", "Set %lld of 3": "Set %lld din 3", "3 sets × 10 reps": "3 seturi × 10 rep",
    "Kegel Timer": "Cronometru Kegel", "kicks": "lovituri",
    "Save Session": "Salvează sesiunea", "Tap for Kick": "Atinge pentru lovitură",
    "Kick Counter": "Contor lovituri", "Track baby movements": "Urmărește mișcările bebelușului",
    "Log weight & view trends": "Înregistrează greutatea și vezi tendințe", "Wellness tools": "Instrumente wellness",
    "Appointment": "Programare", "Development": "Dezvoltare", "Length": "Lungime",
    "How You May Feel": "Cum te poți simți", "Tip": "Sfat",
    "Week %lld Guidance": "Ghid săptămâna %lld",
    "Your weight entries will appear here.": "Înregistrările de greutate vor apărea aici.",
    "Invalid Weight": "Greutate invalidă",
    "Please enter a valid weight in %@.": "Introduceți o greutate validă în %@.",
    "Latest": "Cea mai recentă", "Log Weight": "Înregistrează greutatea",
    "Not logged yet": "Neînregistrat încă",
    "No weight logged yet": "Nicio greutate înregistrată",
    "Or enter manually": "Sau introduceți manual", "Pre-pregnancy": "Pre-sarcină",
    "Previous entry": "Înregistrare anterioară", "Set": "Setează", "Since Last": "De la ultima",
    "%@ since last entry": "%@ de la ultima înregistrare",
    "Since starting weight": "De la greutatea inițială",
    "%@ since starting weight": "%@ de la greutatea inițială", "Starting": "Inițial",
    "Your pre-pregnancy weight helps track healthy gain over time.": "Greutatea pre-sarcină ajută la urmărirea creșterii sănătoase.",
    "Starting Weight": "Greutate inițială",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "Sfat: setează greutatea inițială în Urmărire greutate.",
    "Tap to add": "Atinge pentru a adăuga", "Total Change": "Schimbare totală",
    "Weight Trend": "Tendință greutate",
}
