# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "Arabiska", "bengali": "Bengali", "chinese": "Kinesiska", "dutch": "Nederländska",
    "english": "Engelska", "french": "Franska", "german": "Tyska", "greek": "Grekiska",
    "hebrew": "Hebreiska", "hindi": "Hindi", "indonesian": "Indonesiska", "italian": "Italienska",
    "japanese": "Japanska", "korean": "Koreanska", "malay": "Malajiska", "polish": "Polska",
    "portuguese": "Portugisiska", "romanian": "Rumänska", "russian": "Ryska",
    "spanish": "Spanska", "swedish": "Svenska", "thai": "Thailändska", "turkish": "Turkiska",
    "ukrainian": "Ukrainska", "vietnamese": "Vietnamesiska",
}
TABLE = {
    "Enter a weight between %@ and %@.": "Ange en vikt mellan %1$@ och %2$@.",
    "Step %lld of %lld": "Steg %1$lld av %2$lld",
    "Share with Partner": "Dela med partner",
    "Camera": "Kamera",
    "Add your first photo to start your visual journal.": "Lägg till ditt första foto för att starta din visuella dagbok.",
    "No bump photos yet": "Inga magfoton ännu",
    "Optional note": "Valfri anteckning",
    "Photo Library": "Bildbibliotek",
    "Save Photo": "Spara foto",
    "Capture your growing bump each week and watch your journey unfold.": "Fånga din växande mage varje vecka och följ din resa.",
    "Week %lld Bump": "Vecka %lld mage",
    "Back": "Tillbaka", "Cancel": "Avbryt", "Continue": "Fortsätt", "Date": "Datum",
    "Done!": "Klart!", "Gender": "Kön", "History": "Historik", "Letter": "Bokstav",
    "Log": "Logga", "Logged": "Loggad", "ongoing": "pågående",
    "(optional)": "(valfritt)", "Pause": "Paus",
    "%@ is part of Bloomly Plus": "%@ ingår i Bloomly Plus",
    "Reset": "Återställ", "Save": "Spara", "Severity": "Allvarlighetsgrad",
    "Start": "Start", "Style": "Stil", "Upgrade": "Uppgradera", "Week %lld": "Vecka %lld",
    "Period ended": "Mensen slut", "Day Summary": "Dagssammanfattning", "Notes": "Anteckningar",
    "Daily Log": "Daglig logg", "Daily goal: 8 glasses": "Dagsmål: 8 glas",
    "Daily Tip": "Dagstips", "%lld days until due date": "%lld dagar till beräknat datum",
    "Your due date has passed": "Ditt beräknade datum har passerat", "glasses of water": "glas vatten",
    "How are you feeling?": "Hur mår du?", "Mood": "Humör", "Planning Mode": "Planeringsläge",
    "Track your cycle and prepare for your journey.": "Spåra din cykel och förbered dig för resan.",
    "Pregnancy Progress": "Graviditetsframsteg", "Quick Log": "Snabb logg",
    "Symptoms": "Symtom", "Home": "Hem", "Water": "Vatten", "Water Intake": "Vattenintag",
    "Week %lld of 40": "Vecka %lld av 40", "Weight": "Vikt",
    "Due date": "Beräknat datum", "Last period": "Senaste mens",
    "Last period start": "Senaste mensstart", "Last menstrual period": "Senaste mens",
    "When did your last period start? You can log more dates anytime.": "När började din senaste mens? Du kan logga fler datum när som helst.",
    "Cycle insights appear on your Home tab": "Cykelinsikter visas på fliken Hem",
    "Track your cycle": "Spåra din cykel",
    "We'll calculate your week and due date.": "Vi beräknar din vecka och ditt beräknade datum.",
    "When did your journey begin?": "När började din resa?",
    "Baby size, tips & milestones": "Bebisstorlek, tips och milstolpar",
    "Week-by-week guides": "Vecka för vecka-guider",
    "Symptoms, mood, water & more": "Symtom, humör, vatten och mer",
    "Daily wellness logging": "Daglig wellness-loggning",
    "Your data never leaves your phone": "Dina data lämnar aldrig telefonen",
    "100% on your device": "100% på din enhet", "Get Started": "Kom igång",
    "Cycle tracking, fertile windows & prep": "Cykelspårning, fertila fönster och förberedelse",
    "I'm planning": "Jag planerar",
    "Track weeks, baby size, kicks & milestones": "Spåra veckor, bebisstorlek, sparkar och milstolpar",
    "I'm pregnant": "Jag är gravid",
    "We'll tailor Bloomly to your stage.": "Vi anpassar Bloomly till din fas.",
    "What brings you here?": "Vad för dig hit?", "Daily reminders": "Dagliga påminnelser",
    "First pregnancy?": "Första graviditeten?",
    "This is my first pregnancy": "Det här är min första graviditet",
    "We'll ask for notification permission when you finish setup.": "Vi ber om notisbehörighet när du avslutar installationen.",
    "Starting weight": "Startvikt",
    "Pre-pregnancy weight helps track healthy gain over time.": "Vikt före graviditet hjälper att spåra hälsosam viktuppgång.",
    "A few quick preferences to personalize Bloomly.": "Några snabba inställningar för att anpassa Bloomly.",
    "Almost there!": "Nästan klart!", "Weight unit": "Viktenhet",
    "Key dates": "Viktiga datum", "Your journey": "Din resa",
    "Preferences": "Inställningar", "Welcome": "Välkommen",
    "A calm, private space to track every moment — from first flutter to final countdown.": "Ett lugnt, privat utrymme för varje ögonblick — från första fladder till sista nedräkningen.",
    "Your journey starts here": "Din resa börjar här",
    "Due date has passed — any day now!": "Beräknat datum passerat — vilken dag som helst!",
    "— For %@": "— För %@", "Can't wait to meet our little one!": "Kan inte vänta på att träffa vår lilla!",
    "Personal message": "Personligt meddelande", "Share Image": "Dela bild",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — Vecka %lld",
    "Bloomly Week %lld": "Bloomly Vecka %lld",
    "Share Text Update": "Dela textuppdatering", "Share Update": "Dela uppdatering",
    "Appointments with reminders": "Bokningar med påminnelser",
    "Trimester-aware nutrition guide": "Näringsguide per trimester",
    "Statistics & history charts": "Statistik och historikdiagram",
    "Full symptom & weight logging": "Fullständig symtom- och viktloggning",
    "Wellness tools: Kegel, kick & contraction timers": "Wellness-verktyg: Kegel, spark- och värktimer",
    "Purchase could not be completed.": "Köpet kunde inte slutföras.",
    "Restore Purchases": "Återställ köp", "Start Free": "Börja gratis",
    "Subscriptions will appear when configured in App Store Connect.": "Prenumerationer visas när de konfigureras i App Store Connect.",
    "Unlock the full wellness experience": "Lås upp hela wellness-upplevelsen",
    "Account": "Konto", "Appointments": "Bokningar", "Baby Names": "Babynamn",
    "Bump Journal": "Magedagbok", "Cycle Tracker": "Cykelspårning",
    "Daily Reminders": "Dagliga påminnelser", "Due Date": "Beräknat datum",
    "Favorites": "Favoriter", "Features": "Funktioner", "Free": "Gratis",
    "Log Period": "Logga mens", "Mode": "Läge", "New Appointment": "Ny bokning",
    "No upcoming appointments": "Inga kommande bokningar",
    "Nutrition Guide": "Näringsguide",
    "Used when sharing weekly baby-size updates.": "Används vid delning av veckovisa bebisstorleksuppdateringar.",
    "Partner's name (optional)": "Partners namn (valfritt)",
    "Partner Sharing": "Partnerdelning", "Past": "Tidigare", "Planning": "Planering",
    "Pregnant": "Gravid", "Premium": "Premium", "Privacy": "Integritet",
    "Bloomly stores all your data exclusively on your device.": "Bloomly lagrar all din data enbart på din enhet.",
    "Collect any personal data": "Samla in personuppgifter",
    "Send data to servers or the cloud": "Skicka data till servrar eller molnet",
    "Use analytics or tracking SDKs": "Använda analys- eller spårnings-SDK:er",
    "Show advertisements": "Visa annonser",
    "Require an account or login": "Kräva konto eller inloggning",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "Dina data lämnar inte din iPhone om du inte säkerhetskopierar via iCloud eller iTunes.",
    "Your Privacy Matters": "Din integritet är viktig", "We do not:": "Vi gör inte:",
    "Settings": "Inställningar", "Statistics": "Statistik", "Profile": "Profil",
    "Upcoming": "Kommande", "Upgrade to Bloomly Plus": "Uppgradera till Bloomly Plus",
    "Week": "Vecka", "Weight Tracker": "Viktspårning",
    "Your name (optional)": "Ditt namn (valfritt)",
    "Breakfast": "Frukost", "Dinner": "Middag",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "Dagliga påminnelser för att hålla dig hydrerad och äta regelbundet.",
    "Lunch": "Lunch", "Meal Reminders": "Måltidspåminnelser",
    "Meal Schedule": "Måltidsschema",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "Notiser är avstängda. Tryck här för att öppna Inställningar.",
    "Snack": "Mellanmål", "Water Reminders": "Vattenpåminnelser", "Water Schedule": "Vatersschema",
    "Appearance": "Utseende", "Choose a color theme for your app": "Välj färgtema för appen",
    "Language": "Språk",
    "Content like week guides will stay in English until translated.": "Innehåll som veckoguider förblir på engelska tills det översatts.",
    "Your pregnancy companion": "Din graviditetsföljeslagare",
    "Best": "Bäst", "Current": "Nuvarande", "Details": "Detaljer",
    "Fertile Window": "Fertilt fönster", "Gain": "Ökning", "Mood History": "Humörhistorik",
    "Next Period": "Nästa mens", "No symptom data yet": "Ingen symtomdata ännu",
    "No weight data yet. Log from Home or Weight Tracker.": "Ingen viktdata ännu. Logga från Hem eller Viktspårning.",
    "Ovulation Estimate": "Ägglossningsuppskattning", "Prediction": "Prognos",
    "Symptom Frequency": "Symtomfrekvens", "Water Streak": "Vattenstreak",
    "Weight Over Time": "Vikt över tid", "Tools": "Verktyg", "Week Guide": "Veckoguide",
    "Blush": "Rouge", "Coral": "Korall", "Dark": "Mörk", "Forest": "Skog",
    "Lavender": "Lavendel", "Midnight": "Midnatt", "Mint": "Mint", "Peach": "Persika",
    "Rain": "Regn", "Rose Gold": "Roséguld", "Sunset": "Solnedgång", "White": "Vit",
    "Duration: %@": "Varaktighet: %@", "Interval: %@": "Intervall: %@",
    "Start Contraction": "Starta värk", "Stop Contraction": "Stoppa värk",
    "Time contractions": "Mät värkar", "Contraction Timer": "Värktimer",
    "Hydration": "Hydrering",
    "Log water from the Home tab quick actions": "Logga vatten från snabbåtgärder på Hem",
    "Visual water counter": "Visuell vattenräknare", "Complete!": "Klart!",
    "Hold": "Håll", "Hold for 5 seconds, release for 5 seconds": "Håll i 5 sekunder, släpp i 5 sekunder",
    "Ready": "Redo", "Release": "Släpp", "Rep %lld of 10": "Rep %lld av 10",
    "Rest": "Vila", "Set %lld of 3": "Set %lld av 3", "3 sets × 10 reps": "3 set × 10 reps",
    "Kegel Timer": "Kegel-timer", "kicks": "sparkar",
    "Save Session": "Spara session", "Tap for Kick": "Tryck för spark",
    "Kick Counter": "Sparkräknare", "Track baby movements": "Spåra bebisrörelser",
    "Log weight & view trends": "Logga vikt och se trender", "Wellness tools": "Wellness-verktyg",
    "Appointment": "Bokning", "Development": "Utveckling", "Length": "Längd",
    "How You May Feel": "Hur du kan må", "Tip": "Tips",
    "Week %lld Guidance": "Vecka %lld vägledning",
    "Your weight entries will appear here.": "Dina viktposter visas här.",
    "Invalid Weight": "Ogiltig vikt",
    "Please enter a valid weight in %@.": "Ange en giltig vikt i %@.",
    "Latest": "Senaste", "Log Weight": "Logga vikt",
    "Not logged yet": "Inte loggad ännu",
    "No weight logged yet": "Ingen vikt loggad ännu",
    "Or enter manually": "Eller ange manuellt", "Pre-pregnancy": "Före graviditet",
    "Previous entry": "Föregående post", "Set": "Ange", "Since Last": "Sedan senaste",
    "%@ since last entry": "%@ sedan senaste post",
    "Since starting weight": "Sedan startvikt",
    "%@ since starting weight": "%@ sedan startvikt", "Starting": "Start",
    "Your pre-pregnancy weight helps track healthy gain over time.": "Vikt före graviditet hjälper att spåra hälsosam viktuppgång.",
    "Starting Weight": "Startvikt",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "Tips: ange startvikt i Viktspårning.",
    "Tap to add": "Tryck för att lägga till", "Total Change": "Total förändring",
    "Weight Trend": "Vikttrend",
}
