# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "ภาษาอาหรับ", "bengali": "ภาษาเบงกาลี", "chinese": "ภาษาจีน", "dutch": "ภาษาดัตช์",
    "english": "ภาษาอังกฤษ", "french": "ภาษาฝรั่งเศส", "german": "ภาษาเยอรมัน", "greek": "ภาษากรีก",
    "hebrew": "ภาษาฮีบรู", "hindi": "ภาษาฮินดี", "indonesian": "ภาษาอินโดนีเซีย", "italian": "ภาษาอิตาลี",
    "japanese": "ภาษาญี่ปุ่น", "korean": "ภาษาเกาหลี", "malay": "ภาษามาเลย์", "polish": "ภาษาโปแลนด์",
    "portuguese": "ภาษาโปรตุเกส", "romanian": "ภาษาโรมาเนีย", "russian": "ภาษารัสเซีย",
    "spanish": "ภาษาสเปน", "swedish": "ภาษาสวีเดน", "thai": "ภาษาไทย", "turkish": "ภาษาตุรกี",
    "ukrainian": "ภาษายูเครน", "vietnamese": "ภาษาเวียดนาม",
}
TABLE = {
    "Enter a weight between %@ and %@.": "กรอกน้ำหนักระหว่าง %1$@ ถึง %2$@",
    "Step %lld of %lld": "ขั้นตอน %1$lld จาก %2$lld",
    "Share with Partner": "แชร์กับคู่ครอง",
    "Camera": "กล้อง",
    "Add your first photo to start your visual journal.": "เพิ่มรูปแรกเพื่อเริ่มไดอารี่ภาพของคุณ",
    "No bump photos yet": "ยังไม่มีรูปท้อง",
    "Optional note": "บันทึกเพิ่มเติม (ไม่บังคับ)",
    "Photo Library": "คลังรูปภาพ",
    "Save Photo": "บันทึกรูป",
    "Capture your growing bump each week and watch your journey unfold.": "ถ่ายท้องที่โตขึ้นทุกสัปดาห์และติดตามการเดินทางของคุณ",
    "Week %lld Bump": "ท้องสัปดาห์ที่ %lld",
    "Back": "ย้อนกลับ", "Cancel": "ยกเลิก", "Continue": "ดำเนินการต่อ", "Date": "วันที่",
    "Done!": "เสร็จแล้ว!", "Gender": "เพศ", "History": "ประวัติ", "Letter": "ตัวอักษร",
    "Log": "บันทึก", "Logged": "บันทึกแล้ว", "ongoing": "กำลังดำเนินอยู่",
    "(optional)": "(ไม่บังคับ)", "Pause": "หยุดชั่วคราว",
    "%@ is part of Bloomly Plus": "%@ เป็นส่วนหนึ่งของ Bloomly Plus",
    "Reset": "รีเซ็ต", "Save": "บันทึก", "Severity": "ความรุนแรง",
    "Start": "เริ่ม", "Style": "สไตล์", "Upgrade": "อัปเกรด", "Week %lld": "สัปดาห์ที่ %lld",
    "Period ended": "ประจำเดือนสิ้นสุด", "Day Summary": "สรุปวัน", "Notes": "บันทึก",
    "Daily Log": "บันทึกประจำวัน", "Daily goal: 8 glasses": "เป้าหมายรายวัน: 8 แก้ว",
    "Daily Tip": "เคล็ดลับประจำวัน", "%lld days until due date": "อีก %lld วันถึงวันครบกำหนด",
    "Your due date has passed": "วันครบกำหนดของคุณผ่านไปแล้ว", "glasses of water": "แก้วน้ำ",
    "How are you feeling?": "คุณรู้สึกอย่างไร?", "Mood": "อารมณ์", "Planning Mode": "โหมดวางแผน",
    "Track your cycle and prepare for your journey.": "ติดตามรอบเดือนและเตรียมพร้อมสำหรับการเดินทาง",
    "Pregnancy Progress": "ความคืบหน้าการตั้งครรภ์", "Quick Log": "บันทึกด่วน",
    "Symptoms": "อาการ", "Home": "หน้าแรก", "Water": "น้ำ", "Water Intake": "ปริมาณน้ำ",
    "Week %lld of 40": "สัปดาห์ที่ %lld จาก 40", "Weight": "น้ำหนัก",
    "Due date": "วันครบกำหนด", "Last period": "ประจำเดือนครั้งล่าสุด",
    "Last period start": "วันเริ่มประจำเดือนล่าสุด", "Last menstrual period": "ประจำเดือนครั้งล่าสุด",
    "When did your last period start? You can log more dates anytime.": "ประจำเดือนครั้งล่าสุดเริ่มเมื่อไหร่? บันทึกวันที่เพิ่มได้ทุกเมื่อ",
    "Cycle insights appear on your Home tab": "ข้อมูลรอบเดือนแสดงในแท็บหน้าแรก",
    "Track your cycle": "ติดตามรอบเดือน",
    "We'll calculate your week and due date.": "เราจะคำนวณสัปดาห์และวันครบกำหนด",
    "When did your journey begin?": "การเดินทางของคุณเริ่มเมื่อไหร่?",
    "Baby size, tips & milestones": "ขนาดทารก เคล็ดลับ และเหตุการณ์สำคัญ",
    "Week-by-week guides": "คู่มือรายสัปดาห์",
    "Symptoms, mood, water & more": "อาการ อารมณ์ น้ำ และอื่นๆ",
    "Daily wellness logging": "บันทึกสุขภาพประจำวัน",
    "Your data never leaves your phone": "ข้อมูลของคุณไม่เคยออกจากโทรศัพท์",
    "100% on your device": "100% บนอุปกรณ์ของคุณ", "Get Started": "เริ่มต้น",
    "Cycle tracking, fertile windows & prep": "ติดตามรอบเดือน ช่วงเจริญพันธุ์ และเตรียมตัว",
    "I'm planning": "ฉันกำลังวางแผน",
    "Track weeks, baby size, kicks & milestones": "ติดตามสัปดาห์ ขนาดทารก การดิ้น และเหตุการณ์สำคัญ",
    "I'm pregnant": "ฉันตั้งครรภ์",
    "We'll tailor Bloomly to your stage.": "เราจะปรับ Bloomly ให้เหมาะกับช่วงของคุณ",
    "What brings you here?": "อะไรพาคุณมาที่นี่?", "Daily reminders": "การแจ้งเตือนรายวัน",
    "First pregnancy?": "ตั้งครรภ์ครั้งแรก?",
    "This is my first pregnancy": "นี่เป็นการตั้งครรภ์ครั้งแรกของฉัน",
    "We'll ask for notification permission when you finish setup.": "เราจะขออนุญาตการแจ้งเตือนเมื่อตั้งค่าเสร็จ",
    "Starting weight": "น้ำหนักเริ่มต้น",
    "Pre-pregnancy weight helps track healthy gain over time.": "น้ำหนักก่อนตั้งครรภ์ช่วยติดตามการเพิ่มที่สุขภาพดี",
    "A few quick preferences to personalize Bloomly.": "ตั้งค่าเล็กน้อยเพื่อปรับ Bloomly ให้เป็นของคุณ",
    "Almost there!": "ใกล้เสร็จแล้ว!", "Weight unit": "หน่วยน้ำหนัก",
    "Key dates": "วันที่สำคัญ", "Your journey": "การเดินทางของคุณ",
    "Preferences": "การตั้งค่า", "Welcome": "ยินดีต้อนรับ",
    "A calm, private space to track every moment — from first flutter to final countdown.": "พื้นที่สงบและเป็นส่วนตัวสำหรับทุกช่วงเวลา — ตั้งแต่การดิ้นครั้งแรกจนถึงนับถอยหลัง",
    "Your journey starts here": "การเดินทางของคุณเริ่มที่นี่",
    "Due date has passed — any day now!": "วันครบกำหนดผ่านไปแล้ว — ได้ทุกเมื่อ!",
    "— For %@": "— สำหรับ %@", "Can't wait to meet our little one!": "แทบรอไม่ไหวที่จะได้พบลูกน้อย!",
    "Personal message": "ข้อความส่วนตัว", "Share Image": "แชร์รูป",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — สัปดาห์ที่ %lld",
    "Bloomly Week %lld": "Bloomly สัปดาห์ที่ %lld",
    "Share Text Update": "แชร์ข้อความอัปเดต", "Share Update": "แชร์อัปเดต",
    "Appointments with reminders": "นัดหมายพร้อมการแจ้งเตือน",
    "Trimester-aware nutrition guide": "คู่มือโภชนาการตามไตรมาส",
    "Statistics & history charts": "สถิติและกราฟประวัติ",
    "Full symptom & weight logging": "บันทึกอาการและน้ำหนักครบถ้วน",
    "Wellness tools: Kegel, kick & contraction timers": "เครื่องมือสุขภาพ: Kegel นับการดิ้น และจับเวลาคลื่นไส้",
    "Purchase could not be completed.": "ไม่สามารถซื้อได้",
    "Restore Purchases": "กู้คืนการซื้อ", "Start Free": "เริ่มฟรี",
    "Subscriptions will appear when configured in App Store Connect.": "การสมัครจะแสดงเมื่อตั้งค่าใน App Store Connect",
    "Unlock the full wellness experience": "ปลดล็อกประสบการณ์สุขภาพเต็มรูปแบบ",
    "Account": "บัญชี", "Appointments": "นัดหมาย", "Baby Names": "ชื่อทารก",
    "Bump Journal": "ไดอารี่ท้อง", "Cycle Tracker": "ติดตามรอบเดือน",
    "Daily Reminders": "การแจ้งเตือนรายวัน", "Due Date": "วันครบกำหนด",
    "Favorites": "รายการโปรด", "Features": "ฟีเจอร์", "Free": "ฟรี",
    "Log Period": "บันทึกประจำเดือน", "Mode": "โหมด", "New Appointment": "นัดหมายใหม่",
    "No upcoming appointments": "ไม่มีนัดหมายที่จะมาถึง",
    "Nutrition Guide": "คู่มือโภชนาการ",
    "Used when sharing weekly baby-size updates.": "ใช้เมื่อแชร์อัปเดตขนาดทารกรายสัปดาห์",
    "Partner's name (optional)": "ชื่อคู่ครอง (ไม่บังคับ)",
    "Partner Sharing": "แชร์กับคู่ครอง", "Past": "ที่ผ่านมา", "Planning": "วางแผน",
    "Pregnant": "ตั้งครรภ์", "Premium": "พรีเมียม", "Privacy": "ความเป็นส่วนตัว",
    "Bloomly stores all your data exclusively on your device.": "Bloomly เก็บข้อมูลทั้งหมดบนอุปกรณ์ของคุณเท่านั้น",
    "Collect any personal data": "เก็บข้อมูลส่วนบุคคล",
    "Send data to servers or the cloud": "ส่งข้อมูลไปเซิร์ฟเวอร์หรือคลาวด์",
    "Use analytics or tracking SDKs": "ใช้ analytics หรือ SDK ติดตาม",
    "Show advertisements": "แสดงโฆษณา",
    "Require an account or login": "ต้องมีบัญชีหรือเข้าสู่ระบบ",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "ข้อมูลไม่ออกจาก iPhone เว้นแต่สำรองผ่าน iCloud หรือ iTunes",
    "Your Privacy Matters": "ความเป็นส่วนตัวของคุณสำคัญ", "We do not:": "เราไม่:",
    "Settings": "การตั้งค่า", "Statistics": "สถิติ", "Profile": "โปรไฟล์",
    "Upcoming": "ที่จะมาถึง", "Upgrade to Bloomly Plus": "อัปเกรดเป็น Bloomly Plus",
    "Week": "สัปดาห์", "Weight Tracker": "ติดตามน้ำหนัก",
    "Your name (optional)": "ชื่อของคุณ (ไม่บังคับ)",
    "Breakfast": "อาหารเช้า", "Dinner": "อาหารเย็น",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "แจ้งเตือนรายวันเพื่อให้ดื่มน้ำและกินตรงเวลา",
    "Lunch": "อาหารกลางวัน", "Meal Reminders": "แจ้งเตือนมื้ออาหาร",
    "Meal Schedule": "ตารางมื้ออาหาร",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "การแจ้งเตือนปิดอยู่ แตะที่นี่เพื่อเปิดการตั้งค่า",
    "Snack": "ของว่าง", "Water Reminders": "แจ้งเตือนดื่มน้ำ", "Water Schedule": "ตารางดื่มน้ำ",
    "Appearance": "รูปลักษณ์", "Choose a color theme for your app": "เลือกธีมสีสำหรับแอป",
    "Language": "ภาษา",
    "Content like week guides will stay in English until translated.": "เนื้อหาเช่นคู่มือรายสัปดาห์จะยังเป็นภาษาอังกฤษจนกว่าจะแปล",
    "Your pregnancy companion": "เพื่อนร่วมทางการตั้งครรภ์ของคุณ",
    "Best": "ดีที่สุด", "Current": "ปัจจุบัน", "Details": "รายละเอียด",
    "Fertile Window": "ช่วงเจริญพันธุ์", "Gain": "เพิ่มขึ้น", "Mood History": "ประวัติอารมณ์",
    "Next Period": "ประจำเดือนครั้งถัดไป", "No symptom data yet": "ยังไม่มีข้อมูลอาการ",
    "No weight data yet. Log from Home or Weight Tracker.": "ยังไม่มีข้อมูลน้ำหนัก บันทึกจากหน้าแรกหรือติดตามน้ำหนัก",
    "Ovulation Estimate": "ประมาณการตกไข่", "Prediction": "คาดการณ์",
    "Symptom Frequency": "ความถี่ของอาการ", "Water Streak": "สถิติดื่มน้ำต่อเนื่อง",
    "Weight Over Time": "น้ำหนักตามเวลา", "Tools": "เครื่องมือ", "Week Guide": "คู่มือรายสัปดาห์",
    "Blush": "บลัช", "Coral": "ปะการัง", "Dark": "มืด", "Forest": "ป่า",
    "Lavender": "ลาเวนเดอร์", "Midnight": "เที่ยงคืน", "Mint": "มินต์", "Peach": "พีช",
    "Rain": "ฝน", "Rose Gold": "โร즈โกลด์", "Sunset": "พระอาทิตย์ตก", "White": "ขาว",
    "Duration: %@": "ระยะเวลา: %@", "Interval: %@": "ช่วงห่าง: %@",
    "Start Contraction": "เริ่มคลื่นไส้", "Stop Contraction": "หยุดคลื่นไส้",
    "Time contractions": "จับเวลาคลื่นไส้", "Contraction Timer": "ตัวจับเวลาคลื่นไส้",
    "Hydration": "การดื่มน้ำ",
    "Log water from the Home tab quick actions": "บันทึกน้ำจากการดำเนินการด่วนในแท็บหน้าแรก",
    "Visual water counter": "ตัวนับน้ำแบบภาพ", "Complete!": "เสร็จสมบูรณ์!",
    "Hold": "กลั้น", "Hold for 5 seconds, release for 5 seconds": "กลั้น 5 วินาที คลาย 5 วินาที",
    "Ready": "พร้อม", "Release": "คลาย", "Rep %lld of 10": "ครั้งที่ %lld จาก 10",
    "Rest": "พัก", "Set %lld of 3": "เซ็ต %lld จาก 3", "3 sets × 10 reps": "3 เซ็ต × 10 ครั้ง",
    "Kegel Timer": "ตัวจับเวลา Kegel", "kicks": "การดิ้น",
    "Save Session": "บันทึกเซสชัน", "Tap for Kick": "แตะเมื่อดิ้น",
    "Kick Counter": "ตัวนับการดิ้น", "Track baby movements": "ติดตามการเคลื่อนไหวของทารก",
    "Log weight & view trends": "บันทึกน้ำหนักและดูแนวโน้ม", "Wellness tools": "เครื่องมือสุขภาพ",
    "Appointment": "นัดหมาย", "Development": "พัฒนาการ", "Length": "ความยาว",
    "How You May Feel": "คุณอาจรู้สึกอย่างไร", "Tip": "เคล็ดลับ",
    "Week %lld Guidance": "คำแนะนำสัปดาห์ที่ %lld",
    "Your weight entries will appear here.": "รายการน้ำหนักจะแสดงที่นี่",
    "Invalid Weight": "น้ำหนักไม่ถูกต้อง",
    "Please enter a valid weight in %@.": "กรอกน้ำหนักที่ถูกต้องใน %@",
    "Latest": "ล่าสุด", "Log Weight": "บันทึกน้ำหนัก",
    "Not logged yet": "ยังไม่ได้บันทึก",
    "No weight logged yet": "ยังไม่มีน้ำหนักที่บันทึก",
    "Or enter manually": "หรือกรอกเอง", "Pre-pregnancy": "ก่อนตั้งครรภ์",
    "Previous entry": "รายการก่อนหน้า", "Set": "ตั้งค่า", "Since Last": "ตั้งแต่ครั้งล่าสุด",
    "%@ since last entry": "%@ ตั้งแต่รายการล่าสุด",
    "Since starting weight": "ตั้งแต่น้ำหนักเริ่มต้น",
    "%@ since starting weight": "%@ ตั้งแต่น้ำหนักเริ่มต้น", "Starting": "เริ่มต้น",
    "Your pre-pregnancy weight helps track healthy gain over time.": "น้ำหนักก่อนตั้งครรภ์ช่วยติดตามการเพิ่มที่สุขภาพดี",
    "Starting Weight": "น้ำหนักเริ่มต้น",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "เคล็ดลับ: ตั้งน้ำหนักเริ่มต้นในติดตามน้ำหนัก",
    "Tap to add": "แตะเพื่อเพิ่ม", "Total Change": "การเปลี่ยนแปลงรวม",
    "Weight Trend": "แนวโน้มน้ำหนัก",
}
