# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "Арабська", "bengali": "Бенгальська", "chinese": "Китайська", "dutch": "Нідерландська",
    "english": "Англійська", "french": "Французька", "german": "Німецька", "greek": "Грецька",
    "hebrew": "Іврит", "hindi": "Гінді", "indonesian": "Індонезійська", "italian": "Італійська",
    "japanese": "Японська", "korean": "Корейська", "malay": "Малайська", "polish": "Польська",
    "portuguese": "Португальська", "romanian": "Румунська", "russian": "Російська",
    "spanish": "Іспанська", "swedish": "Шведська", "thai": "Тайська", "turkish": "Турецька",
    "ukrainian": "Українська", "vietnamese": "В'єтнамська",
}
TABLE = {
    "Enter a weight between %@ and %@.": "Введіть вагу між %1$@ та %2$@.",
    "Step %lld of %lld": "Крок %1$lld з %2$lld",
    "Share with Partner": "Поділитися з партнером",
    "Camera": "Камера",
    "Add your first photo to start your visual journal.": "Додайте перше фото, щоб розпочати візуальний щоденник.",
    "No bump photos yet": "Ще немає фото живота",
    "Optional note": "Необов'язкова нотатка",
    "Photo Library": "Фотогалерея",
    "Save Photo": "Зберегти фото",
    "Capture your growing bump each week and watch your journey unfold.": "Фіксуйте зростаючий живіт щотижня та спостерігайте за своєю подорожжю.",
    "Week %lld Bump": "Живіт тижня %lld",
    "Back": "Назад", "Cancel": "Скасувати", "Continue": "Продовжити", "Date": "Дата",
    "Done!": "Готово!", "Gender": "Стать", "History": "Історія", "Letter": "Літера",
    "Log": "Записати", "Logged": "Записано", "ongoing": "триває",
    "(optional)": "(необов'язково)", "Pause": "Пауза",
    "%@ is part of Bloomly Plus": "%@ — частина Bloomly Plus",
    "Reset": "Скинути", "Save": "Зберегти", "Severity": "Тяжкість",
    "Start": "Почати", "Style": "Стиль", "Upgrade": "Оновити", "Week %lld": "Тиждень %lld",
    "Period ended": "Менструація закінчилась", "Day Summary": "Підсумок дня", "Notes": "Нотатки",
    "Daily Log": "Щоденник", "Daily goal: 8 glasses": "Щоденна ціль: 8 склянок",
    "Daily Tip": "Порада дня", "%lld days until due date": "%lld днів до пологів",
    "Your due date has passed": "Ваш термін пологів минув", "glasses of water": "склянок води",
    "How are you feeling?": "Як ви себе почуваєте?", "Mood": "Настрій", "Planning Mode": "Режим планування",
    "Track your cycle and prepare for your journey.": "Відстежуйте цикл і готуйтесь до подорожі.",
    "Pregnancy Progress": "Прогрес вагітності", "Quick Log": "Швидкий запис",
    "Symptoms": "Симптоми", "Home": "Головна", "Water": "Вода", "Water Intake": "Споживання води",
    "Week %lld of 40": "Тиждень %lld з 40", "Weight": "Вага",
    "Due date": "Термін пологів", "Last period": "Остання менструація",
    "Last period start": "Початок останньої менструації", "Last menstrual period": "Остання менструація",
    "When did your last period start? You can log more dates anytime.": "Коли почалась остання менструація? Можете записувати дати будь-коли.",
    "Cycle insights appear on your Home tab": "Дані про цикл з'являються на вкладці Головна",
    "Track your cycle": "Відстежуйте цикл",
    "We'll calculate your week and due date.": "Ми розрахуємо тиждень і термін пологів.",
    "When did your journey begin?": "Коли розпочалась ваша подорож?",
    "Baby size, tips & milestones": "Розмір дитини, поради та віхи",
    "Week-by-week guides": "Тижневі гіди",
    "Symptoms, mood, water & more": "Симптоми, настрій, вода та інше",
    "Daily wellness logging": "Щоденний запис самопочуття",
    "Your data never leaves your phone": "Ваші дані ніколи не залишають телефон",
    "100% on your device": "100% на вашому пристрої", "Get Started": "Почати",
    "Cycle tracking, fertile windows & prep": "Відстеження циклу, фертильні вікна та підготовка",
    "I'm planning": "Я планую",
    "Track weeks, baby size, kicks & milestones": "Відстежуйте тижні, розмір, поштовхи та віхи",
    "I'm pregnant": "Я вагітна",
    "We'll tailor Bloomly to your stage.": "Ми адаптуємо Bloomly до вашого етапу.",
    "What brings you here?": "Що привело вас сюди?", "Daily reminders": "Щоденні нагадування",
    "First pregnancy?": "Перша вагітність?",
    "This is my first pregnancy": "Це моя перша вагітність",
    "We'll ask for notification permission when you finish setup.": "Ми попросимо дозвіл на сповіщення після налаштування.",
    "Starting weight": "Початкова вага",
    "Pre-pregnancy weight helps track healthy gain over time.": "Вага до вагітності допомагає відстежувати здорове зростання.",
    "A few quick preferences to personalize Bloomly.": "Кілька швидких налаштувань для персоналізації Bloomly.",
    "Almost there!": "Майже готово!", "Weight unit": "Одиниця ваги",
    "Key dates": "Ключові дати", "Your journey": "Ваша подорож",
    "Preferences": "Налаштування", "Welcome": "Ласкаво просимо",
    "A calm, private space to track every moment — from first flutter to final countdown.": "Спокійний приватний простір для кожного моменту — від першого руху до зворотного відліку.",
    "Your journey starts here": "Ваша подорож починається тут",
    "Due date has passed — any day now!": "Термін пологів минув — будь-якого дня!",
    "— For %@": "— Для %@", "Can't wait to meet our little one!": "Не можу дочекатися зустрічі з нашою малечею!",
    "Personal message": "Особисте повідомлення", "Share Image": "Поділитися зображенням",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — Тиждень %lld",
    "Bloomly Week %lld": "Bloomly Тиждень %lld",
    "Share Text Update": "Поділитися текстовим оновленням", "Share Update": "Поділитися оновленням",
    "Appointments with reminders": "Записи з нагадуваннями",
    "Trimester-aware nutrition guide": "Гід з харчування за триместрами",
    "Statistics & history charts": "Статистика та графіки історії",
    "Full symptom & weight logging": "Повний запис симптомів і ваги",
    "Wellness tools: Kegel, kick & contraction timers": "Інструменти: Kegel, поштовхи та таймер переймів",
    "Purchase could not be completed.": "Покупку не вдалося завершити.",
    "Restore Purchases": "Відновити покупки", "Start Free": "Почати безкоштовно",
    "Subscriptions will appear when configured in App Store Connect.": "Підписки з'являться після налаштування в App Store Connect.",
    "Unlock the full wellness experience": "Відкрийте повний досвід wellness",
    "Account": "Обліковий запис", "Appointments": "Записи", "Baby Names": "Імена для дитини",
    "Bump Journal": "Щоденник живота", "Cycle Tracker": "Відстеження циклу",
    "Daily Reminders": "Щоденні нагадування", "Due Date": "Термін пологів",
    "Favorites": "Обране", "Features": "Функції", "Free": "Безкоштовно",
    "Log Period": "Записати менструацію", "Mode": "Режим", "New Appointment": "Новий запис",
    "No upcoming appointments": "Немає майбутніх записів",
    "Nutrition Guide": "Гід з харчування",
    "Used when sharing weekly baby-size updates.": "Використовується для щотижневих оновлень розміру дитини.",
    "Partner's name (optional)": "Ім'я партнера (необов'язково)",
    "Partner Sharing": "Спільний доступ з партнером", "Past": "Минуле", "Planning": "Планування",
    "Pregnant": "Вагітна", "Premium": "Преміум", "Privacy": "Конфіденційність",
    "Bloomly stores all your data exclusively on your device.": "Bloomly зберігає всі дані лише на вашому пристрої.",
    "Collect any personal data": "Збираємо персональні дані",
    "Send data to servers or the cloud": "Надсилаємо дані на сервери або в хмару",
    "Use analytics or tracking SDKs": "Використовуємо analytics або SDK відстеження",
    "Show advertisements": "Показуємо рекламу",
    "Require an account or login": "Вимагаємо обліковий запис або вхід",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "Дані не залишають iPhone, якщо не робите резервну копію через iCloud або iTunes.",
    "Your Privacy Matters": "Ваша конфіденційність важлива", "We do not:": "Ми не:",
    "Settings": "Налаштування", "Statistics": "Статистика", "Profile": "Профіль",
    "Upcoming": "Майбутні", "Upgrade to Bloomly Plus": "Оновити до Bloomly Plus",
    "Week": "Тиждень", "Weight Tracker": "Відстеження ваги",
    "Your name (optional)": "Ваше ім'я (необов'язково)",
    "Breakfast": "Сніданок", "Dinner": "Вечеря",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "Щоденні нагадування для води та харчування за розкладом.",
    "Lunch": "Обід", "Meal Reminders": "Нагадування про їжу",
    "Meal Schedule": "Розклад їжі",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "Сповіщення вимкнено. Торкніться тут, щоб відкрити Налаштування.",
    "Snack": "Перекус", "Water Reminders": "Нагадування про воду", "Water Schedule": "Розклад води",
    "Appearance": "Зовнішній вигляд", "Choose a color theme for your app": "Оберіть кольорову тему для застосунку",
    "Language": "Мова",
    "Content like week guides will stay in English until translated.": "Контент на кшталт тижневих гідів залишиться англійською до перекладу.",
    "Your pregnancy companion": "Ваш супутник у вагітності",
    "Best": "Найкраще", "Current": "Поточне", "Details": "Деталі",
    "Fertile Window": "Фертильне вікно", "Gain": "Приріст", "Mood History": "Історія настрою",
    "Next Period": "Наступна менструація", "No symptom data yet": "Ще немає даних про симптоми",
    "No weight data yet. Log from Home or Weight Tracker.": "Ще немає даних про вагу. Записуйте з Головної або Відстеження ваги.",
    "Ovulation Estimate": "Оцінка овуляції", "Prediction": "Прогноз",
    "Symptom Frequency": "Частота симптомів", "Water Streak": "Серія пиття води",
    "Weight Over Time": "Вага з часом", "Tools": "Інструменти", "Week Guide": "Тижневий гід",
    "Blush": "Рум'янець", "Coral": "Корал", "Dark": "Темний", "Forest": "Ліс",
    "Lavender": "Лаванда", "Midnight": "Північ", "Mint": "М'ята", "Peach": "Персик",
    "Rain": "Дощ", "Rose Gold": "Рожеве золото", "Sunset": "Захід", "White": "Білий",
    "Duration: %@": "Тривалість: %@", "Interval: %@": "Інтервал: %@",
    "Start Contraction": "Почати перейми", "Stop Contraction": "Зупинити перейми",
    "Time contractions": "Вимірювання переймів", "Contraction Timer": "Таймер переймів",
    "Hydration": "Гідратація",
    "Log water from the Home tab quick actions": "Записуйте воду з швидких дій на Головній",
    "Visual water counter": "Візуальний лічильник води", "Complete!": "Завершено!",
    "Hold": "Тримати", "Hold for 5 seconds, release for 5 seconds": "Тримайте 5 секунд, відпустіть 5 секунд",
    "Ready": "Готово", "Release": "Відпустити", "Rep %lld of 10": "Повтор %lld з 10",
    "Rest": "Відпочинок", "Set %lld of 3": "Сет %lld з 3", "3 sets × 10 reps": "3 сети × 10 повторів",
    "Kegel Timer": "Таймер Kegel", "kicks": "поштовхи",
    "Save Session": "Зберегти сесію", "Tap for Kick": "Натисніть для поштовху",
    "Kick Counter": "Лічильник поштовхів", "Track baby movements": "Відстеження рухів дитини",
    "Log weight & view trends": "Запис ваги та тренди", "Wellness tools": "Інструменти wellness",
    "Appointment": "Запис", "Development": "Розвиток", "Length": "Довжина",
    "How You May Feel": "Як ви можете почуватися", "Tip": "Порада",
    "Week %lld Guidance": "Поради тижня %lld",
    "Your weight entries will appear here.": "Записи ваги з'являться тут.",
    "Invalid Weight": "Недійсна вага",
    "Please enter a valid weight in %@.": "Введіть дійсну вагу в %@.",
    "Latest": "Останнє", "Log Weight": "Записати вагу",
    "Not logged yet": "Ще не записано",
    "No weight logged yet": "Ще немає записів ваги",
    "Or enter manually": "Або введіть вручну", "Pre-pregnancy": "До вагітності",
    "Previous entry": "Попередній запис", "Set": "Встановити", "Since Last": "З моменту останнього",
    "%@ since last entry": "%@ з останнього запису",
    "Since starting weight": "З початкової ваги",
    "%@ since starting weight": "%@ з початкової ваги", "Starting": "Початкова",
    "Your pre-pregnancy weight helps track healthy gain over time.": "Вага до вагітності допомагає відстежувати здорове зростання.",
    "Starting Weight": "Початкова вага",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "Порада: встановіть початкову вагу у Відстеженні ваги.",
    "Tap to add": "Натисніть, щоб додати", "Total Change": "Загальна зміна",
    "Weight Trend": "Тренд ваги",
}
