# -*- coding: utf-8 -*-
NAMES = {
    "arabic": "Ả Rập", "bengali": "Tiếng Bengal", "chinese": "Trung Quốc", "dutch": "Hà Lan",
    "english": "Tiếng Anh", "french": "Pháp", "german": "Đức", "greek": "Hy Lạp",
    "hebrew": "Do Thái", "hindi": "Tiếng Hindi", "indonesian": "Indonesia", "italian": "Ý",
    "japanese": "Nhật Bản", "korean": "Hàn Quốc", "malay": "Mã Lai", "polish": "Ba Lan",
    "portuguese": "Bồ Đào Nha", "romanian": "Romania", "russian": "Nga",
    "spanish": "Tây Ban Nha", "swedish": "Thụy Điển", "thai": "Thái Lan", "turkish": "Thổ Nhĩ Kỳ",
    "ukrainian": "Ukraina", "vietnamese": "Tiếng Việt",
}
TABLE = {
    "Enter a weight between %@ and %@.": "Nhập cân nặng từ %1$@ đến %2$@.",
    "Step %lld of %lld": "Bước %1$lld / %2$lld",
    "Share with Partner": "Chia sẻ với bạn đời",
    "Camera": "Máy ảnh",
    "Add your first photo to start your visual journal.": "Thêm ảnh đầu tiên để bắt đầu nhật ký hình ảnh.",
    "No bump photos yet": "Chưa có ảnh bụng bầu",
    "Optional note": "Ghi chú (tùy chọn)",
    "Photo Library": "Thư viện ảnh",
    "Save Photo": "Lưu ảnh",
    "Capture your growing bump each week and watch your journey unfold.": "Ghi lại bụng bầu mỗi tuần và theo dõi hành trình của bạn.",
    "Week %lld Bump": "Bụng bầu tuần %lld",
    "Back": "Quay lại", "Cancel": "Hủy", "Continue": "Tiếp tục", "Date": "Ngày",
    "Done!": "Xong!", "Gender": "Giới tính", "History": "Lịch sử", "Letter": "Chữ cái",
    "Log": "Ghi", "Logged": "Đã ghi", "ongoing": "đang diễn ra",
    "(optional)": "(tùy chọn)", "Pause": "Tạm dừng",
    "%@ is part of Bloomly Plus": "%@ là một phần của Bloomly Plus",
    "Reset": "Đặt lại", "Save": "Lưu", "Severity": "Mức độ",
    "Start": "Bắt đầu", "Style": "Kiểu", "Upgrade": "Nâng cấp", "Week %lld": "Tuần %lld",
    "Period ended": "Kỳ kinh đã kết thúc", "Day Summary": "Tóm tắt ngày", "Notes": "Ghi chú",
    "Daily Log": "Nhật ký hàng ngày", "Daily goal: 8 glasses": "Mục tiêu hàng ngày: 8 cốc",
    "Daily Tip": "Mẹo hàng ngày", "%lld days until due date": "Còn %lld ngày đến ngày dự sinh",
    "Your due date has passed": "Ngày dự sinh đã qua", "glasses of water": "cốc nước",
    "How are you feeling?": "Bạn cảm thấy thế nào?", "Mood": "Tâm trạng", "Planning Mode": "Chế độ lập kế hoạch",
    "Track your cycle and prepare for your journey.": "Theo dõi chu kỳ và chuẩn bị cho hành trình.",
    "Pregnancy Progress": "Tiến trình thai kỳ", "Quick Log": "Ghi nhanh",
    "Symptoms": "Triệu chứng", "Home": "Trang chủ", "Water": "Nước", "Water Intake": "Lượng nước uống",
    "Week %lld of 40": "Tuần %lld / 40", "Weight": "Cân nặng",
    "Due date": "Ngày dự sinh", "Last period": "Kỳ kinh gần nhất",
    "Last period start": "Ngày bắt đầu kỳ kinh gần nhất", "Last menstrual period": "Kỳ kinh gần nhất",
    "When did your last period start? You can log more dates anytime.": "Kỳ kinh gần nhất bắt đầu khi nào? Bạn có thể ghi thêm ngày bất cứ lúc nào.",
    "Cycle insights appear on your Home tab": "Thông tin chu kỳ hiển thị ở tab Trang chủ",
    "Track your cycle": "Theo dõi chu kỳ",
    "We'll calculate your week and due date.": "Chúng tôi sẽ tính tuần thai và ngày dự sinh.",
    "When did your journey begin?": "Hành trình của bạn bắt đầu khi nào?",
    "Baby size, tips & milestones": "Kích thước em bé, mẹo và cột mốc",
    "Week-by-week guides": "Hướng dẫn theo tuần",
    "Symptoms, mood, water & more": "Triệu chứng, tâm trạng, nước và hơn nữa",
    "Daily wellness logging": "Ghi chép sức khỏe hàng ngày",
    "Your data never leaves your phone": "Dữ liệu của bạn không bao giờ rời khỏi điện thoại",
    "100% on your device": "100% trên thiết bị của bạn", "Get Started": "Bắt đầu",
    "Cycle tracking, fertile windows & prep": "Theo dõi chu kỳ, thời kỳ màu mỡ và chuẩn bị",
    "I'm planning": "Tôi đang lập kế hoạch",
    "Track weeks, baby size, kicks & milestones": "Theo dõi tuần, kích thước, cử động và cột mốc",
    "I'm pregnant": "Tôi đang mang thai",
    "We'll tailor Bloomly to your stage.": "Chúng tôi sẽ tùy chỉnh Bloomly theo giai đoạn của bạn.",
    "What brings you here?": "Điều gì đưa bạn đến đây?", "Daily reminders": "Nhắc nhở hàng ngày",
    "First pregnancy?": "Mang thai lần đầu?",
    "This is my first pregnancy": "Đây là lần mang thai đầu tiên của tôi",
    "We'll ask for notification permission when you finish setup.": "Chúng tôi sẽ xin quyền thông báo khi bạn hoàn tất thiết lập.",
    "Starting weight": "Cân nặng ban đầu",
    "Pre-pregnancy weight helps track healthy gain over time.": "Cân nặng trước khi mang thai giúp theo dõi tăng cân lành mạnh.",
    "A few quick preferences to personalize Bloomly.": "Một vài tùy chọn nhanh để cá nhân hóa Bloomly.",
    "Almost there!": "Sắp xong rồi!", "Weight unit": "Đơn vị cân nặng",
    "Key dates": "Ngày quan trọng", "Your journey": "Hành trình của bạn",
    "Preferences": "Tùy chọn", "Welcome": "Chào mừng",
    "A calm, private space to track every moment — from first flutter to final countdown.": "Không gian riêng tư, yên bình cho mọi khoảnh khắc — từ cử động đầu tiên đến đếm ngược cuối cùng.",
    "Your journey starts here": "Hành trình của bạn bắt đầu tại đây",
    "Due date has passed — any day now!": "Ngày dự sinh đã qua — bất cứ lúc nào!",
    "— For %@": "— Dành cho %@", "Can't wait to meet our little one!": "Không thể chờ gặp bé yêu!",
    "Personal message": "Tin nhắn cá nhân", "Share Image": "Chia sẻ ảnh",
    "🌸 Bloomly — Week %lld": "🌸 Bloomly — Tuần %lld",
    "Bloomly Week %lld": "Bloomly Tuần %lld",
    "Share Text Update": "Chia sẻ cập nhật văn bản", "Share Update": "Chia sẻ cập nhật",
    "Appointments with reminders": "Lịch hẹn có nhắc nhở",
    "Trimester-aware nutrition guide": "Hướng dẫn dinh dưỡng theo tam cá nguyệt",
    "Statistics & history charts": "Thống kê và biểu đồ lịch sử",
    "Full symptom & weight logging": "Ghi triệu chứng và cân nặng đầy đủ",
    "Wellness tools: Kegel, kick & contraction timers": "Công cụ sức khỏe: Kegel, đếm cử động và hẹn giờ co thắt",
    "Purchase could not be completed.": "Không thể hoàn tất mua hàng.",
    "Restore Purchases": "Khôi phục mua hàng", "Start Free": "Bắt đầu miễn phí",
    "Subscriptions will appear when configured in App Store Connect.": "Gói đăng ký sẽ hiển thị khi được cấu hình trong App Store Connect.",
    "Unlock the full wellness experience": "Mở khóa trải nghiệm sức khỏe đầy đủ",
    "Account": "Tài khoản", "Appointments": "Lịch hẹn", "Baby Names": "Tên em bé",
    "Bump Journal": "Nhật ký bụng bầu", "Cycle Tracker": "Theo dõi chu kỳ",
    "Daily Reminders": "Nhắc nhở hàng ngày", "Due Date": "Ngày dự sinh",
    "Favorites": "Yêu thích", "Features": "Tính năng", "Free": "Miễn phí",
    "Log Period": "Ghi kỳ kinh", "Mode": "Chế độ", "New Appointment": "Lịch hẹn mới",
    "No upcoming appointments": "Không có lịch hẹn sắp tới",
    "Nutrition Guide": "Hướng dẫn dinh dưỡng",
    "Used when sharing weekly baby-size updates.": "Dùng khi chia sẻ cập nhật kích thước em bé hàng tuần.",
    "Partner's name (optional)": "Tên bạn đời (tùy chọn)",
    "Partner Sharing": "Chia sẻ với bạn đời", "Past": "Đã qua", "Planning": "Lập kế hoạch",
    "Pregnant": "Đang mang thai", "Premium": "Cao cấp", "Privacy": "Quyền riêng tư",
    "Bloomly stores all your data exclusively on your device.": "Bloomly lưu trữ mọi dữ liệu chỉ trên thiết bị của bạn.",
    "Collect any personal data": "Thu thập dữ liệu cá nhân",
    "Send data to servers or the cloud": "Gửi dữ liệu lên máy chủ hoặc đám mây",
    "Use analytics or tracking SDKs": "Sử dụng analytics hoặc SDK theo dõi",
    "Show advertisements": "Hiển thị quảng cáo",
    "Require an account or login": "Yêu cầu tài khoản hoặc đăng nhập",
    "Your data never leaves your iPhone unless you back up via iCloud or iTunes.": "Dữ liệu không rời iPhone trừ khi sao lưu qua iCloud hoặc iTunes.",
    "Your Privacy Matters": "Quyền riêng tư của bạn quan trọng", "We do not:": "Chúng tôi không:",
    "Settings": "Cài đặt", "Statistics": "Thống kê", "Profile": "Hồ sơ",
    "Upcoming": "Sắp tới", "Upgrade to Bloomly Plus": "Nâng cấp lên Bloomly Plus",
    "Week": "Tuần", "Weight Tracker": "Theo dõi cân nặng",
    "Your name (optional)": "Tên của bạn (tùy chọn)",
    "Breakfast": "Bữa sáng", "Dinner": "Bữa tối",
    "Daily local reminders to help you stay hydrated and eat on schedule.": "Nhắc nhở hàng ngày giúp bạn uống đủ nước và ăn đúng giờ.",
    "Lunch": "Bữa trưa", "Meal Reminders": "Nhắc bữa ăn",
    "Meal Schedule": "Lịch ăn uống",
    "Notifications are disabled. Tap here to open Settings and enable them for Bloomly.": "Thông báo đã tắt. Chạm vào đây để mở Cài đặt.",
    "Snack": "Bữa phụ", "Water Reminders": "Nhắc uống nước", "Water Schedule": "Lịch uống nước",
    "Appearance": "Giao diện", "Choose a color theme for your app": "Chọn chủ đề màu cho ứng dụng",
    "Language": "Ngôn ngữ",
    "Content like week guides will stay in English until translated.": "Nội dung như hướng dẫn theo tuần sẽ giữ tiếng Anh cho đến khi được dịch.",
    "Your pregnancy companion": "Người bạn đồng hành thai kỳ",
    "Best": "Tốt nhất", "Current": "Hiện tại", "Details": "Chi tiết",
    "Fertile Window": "Thời kỳ màu mỡ", "Gain": "Tăng", "Mood History": "Lịch sử tâm trạng",
    "Next Period": "Kỳ kinh tiếp theo", "No symptom data yet": "Chưa có dữ liệu triệu chứng",
    "No weight data yet. Log from Home or Weight Tracker.": "Chưa có dữ liệu cân nặng. Ghi từ Trang chủ hoặc Theo dõi cân nặng.",
    "Ovulation Estimate": "Ước tính rụng trứng", "Prediction": "Dự đoán",
    "Symptom Frequency": "Tần suất triệu chứng", "Water Streak": "Chuỗi uống nước",
    "Weight Over Time": "Cân nặng theo thời gian", "Tools": "Công cụ", "Week Guide": "Hướng dẫn tuần",
    "Blush": "Hồng phấn", "Coral": "San hô", "Dark": "Tối", "Forest": "Rừng",
    "Lavender": "Oải hương", "Midnight": "Nửa đêm", "Mint": "Bạc hà", "Peach": "Đào",
    "Rain": "Mưa", "Rose Gold": "Vàng hồng", "Sunset": "Hoàng hôn", "White": "Trắng",
    "Duration: %@": "Thời lượng: %@", "Interval: %@": "Khoảng cách: %@",
    "Start Contraction": "Bắt đầu co thắt", "Stop Contraction": "Dừng co thắt",
    "Time contractions": "Đo co thắt", "Contraction Timer": "Hẹn giờ co thắt",
    "Hydration": "Hydrat hóa",
    "Log water from the Home tab quick actions": "Ghi nước từ thao tác nhanh ở tab Trang chủ",
    "Visual water counter": "Bộ đếm nước trực quan", "Complete!": "Hoàn thành!",
    "Hold": "Giữ", "Hold for 5 seconds, release for 5 seconds": "Giữ 5 giây, thả 5 giây",
    "Ready": "Sẵn sàng", "Release": "Thả", "Rep %lld of 10": "Lần %lld / 10",
    "Rest": "Nghỉ", "Set %lld of 3": "Hiệp %lld / 3", "3 sets × 10 reps": "3 hiệp × 10 lần",
    "Kegel Timer": "Hẹn giờ Kegel", "kicks": "cử động",
    "Save Session": "Lưu phiên", "Tap for Kick": "Chạm khi cử động",
    "Kick Counter": "Đếm cử động", "Track baby movements": "Theo dõi cử động thai nhi",
    "Log weight & view trends": "Ghi cân nặng và xem xu hướng", "Wellness tools": "Công cụ sức khỏe",
    "Appointment": "Lịch hẹn", "Development": "Phát triển", "Length": "Chiều dài",
    "How You May Feel": "Bạn có thể cảm thấy", "Tip": "Mẹo",
    "Week %lld Guidance": "Hướng dẫn tuần %lld",
    "Your weight entries will appear here.": "Mục cân nặng sẽ hiển thị tại đây.",
    "Invalid Weight": "Cân nặng không hợp lệ",
    "Please enter a valid weight in %@.": "Vui lòng nhập cân nặng hợp lệ theo %@.",
    "Latest": "Mới nhất", "Log Weight": "Ghi cân nặng",
    "Not logged yet": "Chưa ghi",
    "No weight logged yet": "Chưa ghi cân nặng",
    "Or enter manually": "Hoặc nhập thủ công", "Pre-pregnancy": "Trước khi mang thai",
    "Previous entry": "Mục trước", "Set": "Đặt", "Since Last": "Kể từ lần trước",
    "%@ since last entry": "%@ kể từ lần ghi trước",
    "Since starting weight": "Kể từ cân nặng ban đầu",
    "%@ since starting weight": "%@ kể từ cân nặng ban đầu", "Starting": "Ban đầu",
    "Your pre-pregnancy weight helps track healthy gain over time.": "Cân nặng trước khi mang thai giúp theo dõi tăng cân lành mạnh.",
    "Starting Weight": "Cân nặng ban đầu",
    "Tip: set your starting weight in the Weight Tracker for gain tracking.": "Mẹo: đặt cân nặng ban đầu trong Theo dõi cân nặng.",
    "Tap to add": "Chạm để thêm", "Total Change": "Tổng thay đổi",
    "Weight Trend": "Xu hướng cân nặng",
}
